/* Teaching content for the Japanese Empire map.
 *
 * The SVG holds "atoms" — the smallest regions any snapshot needs. This file
 * composes them into territories separately for each epoch, so Manchuria can
 * be three Chinese provinces in 1930 and Manchukuo in 1942 without the map
 * carrying two copies of the geometry. Atoms given the same colour in an epoch
 * show no boundary between them, which is how British India comes out as one
 * shape with no line at the Punjab and Indochina as one shape with no line at
 * the Mekong.
 *
 * Every item carries three names:
 *   en    the name in English as it was used at the time, with the present-day
 *         name after it in brackets where they differ — Taihoku (Taipei)
 *   ja    the name used in Japanese, in its imperial-period form
 *   orig  the local name in the local language
 *
 * lvl  1 = basic, 2 = intermediate, 3 = advanced. Levels decide what the quiz
 *      asks for and what is labelled; every territory stays clickable at every
 *      level.
 */

const JMAP = {};

/* The region the map opens on when the whole frame will not fit usefully. */
JMAP.HOME = { lon0: 100, lat0: -4, lon1: 160, lat1: 52 };

JMAP.EPOCHS = [
  {
    id: 'e1930', en: '1930', ja: '1930年', orig: '1930', zh: '1930年', ko: '1930년',
    blurb: 'Before the Manchurian Incident. Japan holds Taiwan, Korea, Karafuto, ' +
           'the Kwantung leasehold and the South Seas Mandate. Everything else in ' +
           'the region belongs to somebody else’s empire, and the colours here show ' +
           'whose.',
  },
  {
    id: 'e1942', en: 'Late 1942', ja: '1942年後半', orig: 'Late 1942', zh: '1942年後期', ko: '1942년 후반',
    blurb: 'The greatest extent of the empire, after the southern advance and ' +
           'before the tide turned at Guadalcanal. Ten years of expansion in China ' +
           'and six months of conquest in Southeast Asia and the Pacific.',
  },
];

JMAP.DEFAULT_EPOCH = 'e1942';

/* Category colours. Palettes are per epoch, because the two maps answer
 * different questions: in 1930 "whose empire is this?", in 1942 "how did Japan
 * hold it?" */
JMAP.CATEGORIES = {
  e1930: [
    { id: 'metropole', c: '#a8322b', en: 'Japan proper', ja: '内地', orig: 'Japan proper', zh: '日本內地', ko: '일본 본토' },
    { id: 'jpcolony', c: '#d9663d', en: 'Japanese colonies', ja: '日本の外地', orig: 'Japanese colonies', zh: '日本殖民地', ko: '일본 식민지' },
    { id: 'chinese', c: '#e8d9a8', en: 'China', ja: '中国', orig: 'China', zh: '中國', ko: '중국' },
    { id: 'british', c: '#b07f8e', en: 'British', ja: 'イギリス領', orig: 'British', zh: '英國領', ko: '영국령' },
    { id: 'french', c: '#7d9cc0', en: 'French', ja: 'フランス領', orig: 'French', zh: '法國領', ko: '프랑스령' },
    { id: 'dutch', c: '#e79f4a', en: 'Dutch', ja: 'オランダ領', orig: 'Dutch', zh: '荷蘭領', ko: '네덜란드령' },
    { id: 'american', c: '#8aab8c', en: 'American', ja: 'アメリカ領', orig: 'American', zh: '美國領', ko: '미국령' },
    { id: 'portuguese', c: '#7b6ba8', en: 'Portuguese', ja: 'ポルトガル領', orig: 'Portuguese', zh: '葡萄牙領', ko: '포르투갈령' },
    { id: 'australian', c: '#c9a227', en: 'Australian', ja: 'オーストラリア領', orig: 'Australian', zh: '澳洲領', ko: '오스트레일리아령' },
    { id: 'soviet', c: '#8f9bb3', en: 'Soviet', ja: 'ソ連', orig: 'Soviet', zh: '蘇聯', ko: '소련' },
    { id: 'independent', c: '#9ec4b8', en: 'Independent', ja: '独立国', orig: 'Independent', zh: '獨立國', ko: '독립국' },
    { id: 'other', c: '#ded8cb', en: 'Elsewhere', ja: 'その他', orig: 'Elsewhere', zh: '其他', ko: '기타' },
  ],
  e1942: [
    { id: 'metropole', c: '#a8322b', en: 'Japan proper', ja: '内地', orig: 'Japan proper', zh: '日本內地', ko: '일본 본토' },
    { id: 'colony', c: '#d9663d', en: 'Colonies & leased territory', ja: '外地・租借地', orig: 'Colonies', zh: '外地・租借地', ko: '외지·조차지' },
    { id: 'puppet', c: '#edc04b', en: 'Client states', ja: '傀儡国家', orig: 'Client states', zh: '傀儡國家', ko: '괴뢰국' },
    { id: 'occupied', c: '#e79f4a', en: 'Under military occupation', ja: '軍政地域', orig: 'Occupied', zh: '軍政地區', ko: '군정 지역' },
    { id: 'contested', c: '#c98f6a', en: 'Fighting front', ja: '戦線', orig: 'Fighting front', zh: '戰線', ko: '전선' },
    { id: 'cobelligerent', c: '#c9a227', en: 'Co-belligerent', ja: '同盟国', orig: 'Co-belligerent', zh: '日本盟國', ko: '일본의 동맹국' },
    { id: 'allied', c: '#9fb4c9', en: 'Allied', ja: '連合国', orig: 'Allied', zh: '盟軍', ko: '연합국' },
    { id: 'neutral', c: '#c3c3b4', en: 'Neutral', ja: '中立', orig: 'Neutral', zh: '中立', ko: '중립' },
    { id: 'other', c: '#ded8cb', en: 'Elsewhere', ja: 'その他', orig: 'Elsewhere', zh: '其他', ko: '기타' },
  ],
};

/* Marker categories, shared by both epochs. */
JMAP.SITE_CATEGORIES = [
  { id: 'city', c: '#1f3d5c', en: 'Cities & ports', ja: '都市・港', orig: 'Cities & ports', zh: '城市・港口', ko: '도시·항구' },
  { id: 'battle', c: '#8e1f57', en: 'Battles & incidents', ja: '戦闘・事件', orig: 'Battles & incidents', zh: '戰役・事件', ko: '전투·사건' },
];

/* ------------------------------------------------------------------ */
/* Territories, per epoch                                              */
/* ------------------------------------------------------------------ */

JMAP.TERRITORIES = {

  /* ============================== 1930 ============================== */
  e1930: [
    { id: 'japan', atoms: ['japan'], cat: 'metropole', lvl: 1,
      en: 'Japan (home islands)', ja: '内地 (Naichi)', orig: '日本 (Nihon)',
      zh: '日本內地', ko: '일본 본토 (Ilbon bont’o)',
      when: 'The metropole',
      note: 'Honshū, Kyūshū, Shikoku and Hokkaidō. Hokkaidō was itself a settler frontier, colonised from 1869 at the expense of the Ainu.' },
    { id: 'ryukyu', atoms: ['ryukyu'], cat: 'metropole', lvl: 1,
      en: 'Loochoo Islands / Okinawa Prefecture', ja: '沖縄県 (Okinawa-ken)', orig: '琉球 (Ruuchuu)',
      zh: '琉球・沖繩縣', ko: '류큐·오키나와현 (Ryukyu / Okinawa-hyŏn)',
      when: 'Annexed 1879',
      note: 'The Ryūkyū Kingdom paid tribute to both China and Satsuma until Japan abolished it and created Okinawa Prefecture in 1879.' },
    { id: 'ogasawara', atoms: ['ogasawara'], cat: 'metropole', lvl: 3,
      en: 'Bonin Islands (Ogasawara)', ja: '小笠原諸島 (Ogasawara Shotō)', orig: '小笠原諸島',
      zh: '小笠原群島', ko: '오가사와라 제도 (Ogasawara Chedo)',
      when: 'Claimed 1876',
      note: 'A scattering of volcanic islands 1,000 km south of Tokyo, including Iwo Jima.' },
    { id: 'chishima', atoms: ['chishima'], cat: 'metropole', lvl: 2,
      en: 'Kurile Islands (Chishima)', ja: '千島列島 (Chishima Rettō)', orig: 'Курильские острова',
      zh: '千島群島', ko: '지시마 열도 (Chisima Yŏldo)',
      when: 'Japanese from 1875',
      note: 'Traded to Japan by Russia in the 1875 Treaty of Saint Petersburg, in exchange for Japanese claims to Sakhalin.' },

    { id: 'chosen', atoms: ['korea'], cat: 'jpcolony', lvl: 1,
      en: 'Chosen (Korea)', ja: '朝鮮 (Chōsen)', orig: '조선 (Chosŏn)',
      zh: '朝鮮', ko: '조선 (Chosŏn)',
      when: 'Protectorate 1905, annexed 1910',
      note: 'Opened by the Kanghwa Treaty of 1876, made a protectorate after the Russo-Japanese War and annexed outright in August 1910. The March First Movement of 1919 was met with mass repression.' },
    { id: 'formosa', atoms: ['taiwan'], cat: 'jpcolony', lvl: 1,
      en: 'Formosa (Taiwan)', ja: '臺灣 (Taiwan)', orig: '臺灣 (Tâi-oân)',
      zh: '臺灣', ko: '대만 (Taeman)',
      when: 'Japanese colony from 1895',
      note: 'Japan’s first modern colony, ceded by the Qing in the 1895 Treaty of Shimonoseki after the First Sino-Japanese War.' },
    { id: 'karafuto', atoms: ['karafuto'], cat: 'jpcolony', lvl: 1,
      en: 'Karafuto (southern Sakhalin)', ja: '樺太 (Karafuto)', orig: 'Южный Сахалин',
      zh: '樺太（南薩哈林）', ko: '가라후토 (Karahuto)',
      when: 'Japanese from 1905',
      note: 'Sakhalin south of the 50th parallel, taken from Russia by the 1905 Treaty of Portsmouth.' },
    { id: 'kwantung', atoms: ['kwantung'], cat: 'jpcolony', lvl: 2,
      en: 'Kwantung Leased Territory', ja: '関東州 (Kantōshū)', orig: '關東州 (Guāndōngzhōu)',
      zh: '關東州', ko: '관동주 (Kwandongju)',
      when: 'Leased from China 1905–1945',
      note: 'The tip of the Liaodong peninsula, leased by Russia in 1898 and transferred to Japan in 1905. Port Arthur and Dairen sat inside it, and so did the garrison that became the Kwantung Army.' },
    { id: 'nanyo', atoms: ['nanyo'], cat: 'jpcolony', lvl: 2,
      en: 'South Seas Mandate (Micronesia)', ja: '南洋群島 (Nan’yō Guntō)', orig: 'Micronesia',
      zh: '南洋群島', ko: '남양군도 (Namyang Kundo)',
      when: 'Seized 1914, mandate from 1919',
      note: 'The Marianas, Carolines and Marshalls, taken from Germany in 1914 and held from 1919 as a League of Nations Class C mandate.' },

    { id: 'china', atoms: ['china', 'occupiedchina'], cat: 'chinese', lvl: 1,
      en: 'China (Republic of China)', ja: '中華民国 (Chūka Minkoku)', orig: '中華民國 (Zhōnghuá Mínguó)',
      zh: '中華民國', ko: '중화민국 (Chunghwa Min’guk)',
      when: 'Republic from 1912',
      note: 'Nominally reunified by the Northern Expedition in 1928, with its capital at Nanking, but in practice a patchwork of regional militarists. Japan had a concession at Tientsin, a garrison in north China and the South Manchuria Railway zone.' },
    { id: 'manchuria', atoms: ['manchuria'], cat: 'chinese', lvl: 1,
      en: 'Manchuria (the Three Eastern Provinces)', ja: '満洲 (Manshū)', orig: '東三省 (Dōngsānshěng)',
      zh: '滿洲（東三省）', ko: '만주 (Manju)',
      when: 'Chinese, under Chang Hsüeh-liang',
      note: 'Chinese territory in 1930, run by the Fengtien clique — Chang Tso-lin until his assassination by Japanese officers in 1928, then his son Chang Hsüeh-liang, who declared for Nanking. Japan already held the railway zone and the Kwantung leasehold inside it. The Kwantung Army invaded in September 1931.' },
    { id: 'jehol', atoms: ['jehol'], cat: 'chinese', lvl: 3,
      en: 'Jehol (Rehe)', ja: '熱河 (Nekka)', orig: '熱河省 (Rèhé shěng)',
      zh: '熱河省', ko: '열하성 (Yŏlha-sŏng)',
      when: 'Chinese province from 1928',
      note: 'The province between the Great Wall and Manchuria, made a full province in 1928. Japan took it in February 1933 and attached it to Manchukuo.' },
    { id: 'chaharsuiyuan', atoms: ['chahar', 'suiyuan'], cat: 'chinese', lvl: 3,
      en: 'Chahar & Suiyuan', ja: '察哈爾・綏遠 (Chaharu, Suien)', orig: '察哈爾・綏遠',
      zh: '察哈爾・綏遠', ko: '차하르·수이위안 (Ch’ahar / Suiwŏn)',
      when: 'Chinese provinces',
      note: 'The Inner Mongolian frontier provinces. From 1936 they became the Japanese client regime of Mengchiang under Prince Demchugdongrub, with its capital at Kalgan.' },
    { id: 'xinjiang', atoms: ['xinjiang'], cat: 'chinese', lvl: 3,
      en: 'Sinkiang (Xinjiang)', ja: '新疆 (Shinkyō)', orig: 'شىنجاڭ (Shinjang)',
      zh: '新疆', ko: '신장 (Sinjang)',
      when: 'Ruled by Yang Zengxin, then Jin Shuren',
      note: 'Nominally a province of the Republic, in practice run as a private domain by a succession of governors who dealt directly with the Soviet Union. Nanking’s writ did not reach it.' },
    { id: 'tibet', atoms: ['tibet'], cat: 'chinese', lvl: 3,
      en: 'Tibet', ja: 'チベット (Chibetto)', orig: 'བོད་ (Bod)',
      zh: '西藏', ko: '티베트 (T’ibet’ŭ)',
      when: 'De facto independent from 1913',
      note: 'Claimed by the Republic of China and shown here in the Chinese colour, but in practice self-governing under the 13th Dalai Lama from 1913 until 1951.' },

    { id: 'britishindia', atoms: ['india', 'andaman', 'burma'], cat: 'british', lvl: 1,
      en: 'British India (including Burma)', ja: '英領インド (Eiryō Indo)', orig: 'भारत (Bhārat)',
      zh: '英屬印度', ko: '영국령 인도 (Yŏnggungnyŏng Indo)',
      when: 'Burma a province of India until 1937',
      note: 'Burma was governed as a province of British India until it was separated in 1937. The Andaman and Nicobar Islands were run from Calcutta as a penal settlement.' },
    { id: 'ceylon', atoms: ['ceylon'], cat: 'british', lvl: 3,
      en: 'Ceylon', ja: 'セイロン (Seiron)', orig: 'ලංකාව (Lanka)',
      zh: '錫蘭', ko: '실론 (Sillon)',
      when: 'Crown colony',
      note: 'A separate Crown colony, not part of British India, and the Royal Navy’s main base in the eastern Indian Ocean.' },
    { id: 'malaya', atoms: ['malaya'], cat: 'british', lvl: 2,
      en: 'British Malaya & Singapore', ja: '英領馬来 (Eiryō Marai)', orig: 'Tanah Melayu / Singapura',
      zh: '馬來亞・新加坡', ko: '말라야·싱가포르 (Mallaya / Singgap’orŭ)',
      when: 'Straits Settlements & protected states',
      note: 'The Straits Settlements and the protected Malay states, with the Singapore naval base begun in 1923 as the anchor of British power east of Suez.' },
    { id: 'borneo_br', atoms: ['borneo_br'], cat: 'british', lvl: 3,
      en: 'British Borneo (Sarawak, Brunei, North Borneo)', ja: '英領ボルネオ', orig: 'Borneo',
      zh: '英屬婆羅洲', ko: '영국령 보르네오 (Yŏnggungnyŏng Borŭneo)',
      when: 'Protectorates & chartered company',
      note: 'Sarawak under the Brooke family, North Borneo under a chartered company, and the protected sultanate of Brunei.' },
    { id: 'hongkong', atoms: ['hongkong'], cat: 'british', lvl: 2,
      en: 'Hong Kong', ja: '香港 (Honkon)', orig: '香港 (Hēunggóng)',
      zh: '香港', ko: '홍콩 (Hongk’ong)',
      when: 'British from 1842',
      note: 'Ceded in 1842 and enlarged by the New Territories lease of 1898.' },
    { id: 'solomons_br', atoms: ['solomons_br'], cat: 'british', lvl: 3,
      en: 'British Solomon Islands', ja: 'ソロモン諸島', orig: 'Solomon Islands',
      zh: '所羅門群島', ko: '솔로몬 제도 (Sollomon Chedo)',
      when: 'Protectorate from 1893',
      note: 'A British protectorate; Guadalcanal would become the turning point of the Pacific War in 1942–43.' },
    { id: 'gilberts', atoms: ['gilberts'], cat: 'british', lvl: 3,
      en: 'Gilbert & Ellice Islands', ja: 'ギルバート諸島', orig: 'Tungaru',
      zh: '吉爾伯特群島', ko: '길버트 제도 (Kilbŏt’ŭ Chedo)',
      when: 'Colony from 1916',
      note: 'A scatter of atolls including Tarawa, taken by Japan in December 1941.' },

    { id: 'indochina', atoms: ['indochina'], cat: 'french', lvl: 1,
      en: 'French Indochina', ja: '仏印 (Futsuin)', orig: 'Đông Dương thuộc Pháp',
      zh: '法屬印度支那', ko: '프랑스령 인도차이나 (P’ŭrangsŭryŏng Indoch’aina)',
      when: 'French from the 1880s',
      note: 'Tonkin, Annam, Cochinchina, Cambodia and Laos under a single Governor-General at Hanoi. Shown as one territory because that is what it was: the borders of Vietnam, Laos and Cambodia are later.' },

    { id: 'dei', atoms: ['dei'], cat: 'dutch', lvl: 1,
      en: 'Netherlands East Indies', ja: '蘭印 (Ran’in)', orig: 'Nederlandsch-Indië',
      zh: '荷屬東印度', ko: '네덜란드령 동인도 (Nedŏllandŭryŏng Tongindo)',
      when: 'Dutch',
      note: 'Java, Sumatra, the Dutch share of Borneo, the eastern islands and western New Guinea. Its oil would be the central economic prize of Japan’s southern advance.' },

    { id: 'philippines', atoms: ['philippines'], cat: 'american', lvl: 1,
      en: 'Philippine Islands', ja: '比島 (Hitō)', orig: 'Pilipinas',
      zh: '菲律賓', ko: '필리핀 (P’illip’in)',
      when: 'American from 1898',
      note: 'Taken from Spain in 1898 and held after a brutal war against Filipino republicans. A commonwealth with promised independence from 1935.' },
    { id: 'guam', atoms: ['guam'], cat: 'american', lvl: 3,
      en: 'Guam', ja: 'グアム (Guamu)', orig: 'Guåhan',
      zh: '關島', ko: '괌 (Kwam)',
      when: 'American from 1898',
      note: 'A US naval station sitting in the middle of the Japanese-held Marianas.' },
    { id: 'hawaii', atoms: ['hawaii'], cat: 'american', lvl: 2,
      en: 'Hawaii', ja: '布哇 (Hawai)', orig: 'Hawaiʻi',
      zh: '夏威夷', ko: '하와이 (Hawai)',
      when: 'Annexed 1898',
      note: 'A US territory with a large Japanese immigrant population, and from 1919 the base of the US Pacific Fleet at Pearl Harbor.' },
    { id: 'aleutians', atoms: ['aleutians'], cat: 'american', lvl: 3,
      en: 'Aleutian Islands', ja: 'アリューシャン列島', orig: 'Unangam Tanangin',
      zh: '阿留申群島', ko: '알류샨 열도 (Allyusyan Yŏldo)',
      when: 'Part of the Alaska Territory',
      note: 'The chain reaching from Alaska towards Kamchatka; Attu and Kiska at its western end would be occupied by Japan in 1942.' },

    { id: 'timor_pt', atoms: ['timor_pt'], cat: 'portuguese', lvl: 3,
      en: 'Portuguese Timor', ja: 'ポルトガル領チモール', orig: 'Timor Português',
      zh: '葡屬帝汶', ko: '포르투갈령 티모르 (P’orŭt’ugallyŏng T’imorŭ)',
      when: 'Portuguese',
      note: 'The eastern half of Timor, and one of the last fragments of the old Portuguese seaborne empire.' },
    { id: 'macau', atoms: ['macau'], cat: 'portuguese', lvl: 3,
      en: 'Macao', ja: 'マカオ (Makao)', orig: '澳門 (Ou-mun)',
      zh: '澳門', ko: '마카오 (Mak’ao)',
      when: 'Portuguese from the 1550s',
      note: 'The oldest European settlement in East Asia, and neutral throughout the Pacific War.' },

    { id: 'siam', atoms: ['siam'], cat: 'independent', lvl: 2,
      en: 'Siam', ja: '暹羅 (Shamu)', orig: 'สยาม (Sayam)',
      zh: '暹羅', ko: '시암 (Siam)',
      when: 'Never colonised',
      note: 'The one state in Southeast Asia that kept its independence, by playing Britain and France against each other and ceding territory to both. Renamed Thailand in 1939.' },

    { id: 'ussr', atoms: ['ussr'], cat: 'soviet', lvl: 1,
      en: 'Soviet Union (USSR)', ja: 'ソビエト連邦 (Sobieto Renpō)', orig: 'СССР (SSSR)',
      zh: '蘇聯', ko: '소련 (Soryŏn)',
      when: 'From 1922',
      note: 'Japan had intervened in the Russian Civil War in Siberia from 1918 to 1922 and held northern Sakhalin until 1925. Relations along the Manchurian border stayed tense.' },
    { id: 'mongolia', atoms: ['mongolia'], cat: 'soviet', lvl: 2,
      en: 'Mongolian People’s Republic (Outer Mongolia)', ja: '蒙古人民共和国', orig: 'Бүгд Найрамдах Монгол Ард Улс',
      zh: '蒙古人民共和國', ko: '몽골인민공화국 (Monggol Inmin Konghwaguk)',
      when: 'From 1924',
      note: 'Independent of China in fact from 1911 and a Soviet satellite from 1924, though only the USSR recognised it.' },

    { id: 'australia', atoms: ['australia'], cat: 'australian', lvl: 2,
      en: 'Australia', ja: '豪州 (Gōshū)', orig: 'Australia',
      zh: '澳大利亞', ko: '오스트레일리아 (Osŭt’ŭreillia)',
      when: 'Dominion',
      note: 'A self-governing dominion whose defence rested on the British naval base at Singapore.' },
    { id: 'newguinea_au', atoms: ['newguinea_au'], cat: 'australian', lvl: 3,
      en: 'Papua & the Territory of New Guinea', ja: 'ニューギニア', orig: 'Niugini',
      zh: '新幾內亞', ko: '뉴기니 (Nyugini)',
      when: 'Australian territory & mandate',
      note: 'Papua was an Australian territory; German New Guinea, taken in 1914, was held from 1920 under a League mandate — the southern counterpart of Japan’s.' },
    { id: 'nauru_au', atoms: ['nauru_au'], cat: 'australian', lvl: 3,
      en: 'Nauru', ja: 'ナウル', orig: 'Naoero',
      zh: '諾魯', ko: '나우루 (Nauru)',
      when: 'Mandate from 1920',
      note: 'A phosphate island held under a mandate shared by Australia, Britain and New Zealand.' },

    { id: 'other', atoms: ['other'], cat: 'other', lvl: 3,
      en: 'Afghanistan, Nepal and Bhutan', ja: 'アフガニスタン・ネパール・ブータン', orig: 'Afghanistan, Nepal, Bhutan',
      zh: '阿富汗・尼泊爾・不丹', ko: '아프가니스탄·네팔·부탄',
      when: '', note: 'Outside the story of the Japanese Empire, drawn for context.' },
  ],

  /* ============================ Late 1942 ============================ */
  e1942: [
    { id: 'japan', atoms: ['japan'], cat: 'metropole', lvl: 1,
      en: 'Japan (home islands)', ja: '内地 (Naichi)', orig: '日本 (Nihon)',
      zh: '日本內地', ko: '일본 본토 (Ilbon bont’o)',
      when: 'The metropole',
      note: 'Untouched by the war so far, apart from the Doolittle raid of April 1942. Systematic bombing would begin once the Marianas fell in 1944.' },
    { id: 'ryukyu', atoms: ['ryukyu'], cat: 'metropole', lvl: 1,
      en: 'Loochoo Islands / Okinawa Prefecture', ja: '沖縄県 (Okinawa-ken)', orig: '琉球 (Ruuchuu)',
      zh: '琉球・沖繩縣', ko: '류큐·오키나와현 (Ryukyu / Okinawa-hyŏn)',
      when: 'Annexed 1879',
      note: 'A prefecture, not a colony, though it was governed and garrisoned as a frontier. The Battle of Okinawa in 1945 killed roughly a quarter of the civilian population.' },
    { id: 'ogasawara', atoms: ['ogasawara'], cat: 'metropole', lvl: 3,
      en: 'Bonin Islands (Ogasawara)', ja: '小笠原諸島 (Ogasawara Shotō)', orig: '小笠原諸島',
      zh: '小笠原群島', ko: '오가사와라 제도 (Ogasawara Chedo)',
      when: 'Claimed 1876',
      note: 'The chain that includes Iwo Jima, fortified as the last barrier on the direct approach to Tokyo.' },
    { id: 'chishima', atoms: ['chishima'], cat: 'metropole', lvl: 2,
      en: 'Kurile Islands (Chishima)', ja: '千島列島 (Chishima Rettō)', orig: 'Курильские острова',
      zh: '千島群島', ko: '지시마 열도 (Chisima Yŏldo)',
      when: 'Japanese from 1875',
      note: 'The Pearl Harbor strike force sailed from Hitokappu Bay in these islands in November 1941. Seized by the USSR in 1945 and still disputed.' },

    { id: 'chosen', atoms: ['korea'], cat: 'colony', lvl: 1,
      en: 'Chosen (Korea)', ja: '朝鮮 (Chōsen)', orig: '조선 (Chosŏn)',
      zh: '朝鮮', ko: '조선 (Chosŏn)',
      when: 'Annexed 1910–1945',
      note: 'By 1942 under the assimilation drive: Korean-language teaching suppressed, Japanese names imposed from 1940, and mobilisation of labour and, from 1944, conscription.' },
    { id: 'formosa', atoms: ['taiwan'], cat: 'colony', lvl: 1,
      en: 'Formosa (Taiwan)', ja: '臺灣 (Taiwan)', orig: '臺灣 (Tâi-oân)',
      zh: '臺灣', ko: '대만 (Taeman)',
      when: 'Japanese colony 1895–1945',
      note: 'The oldest colony and the staging ground for the invasion of the Philippines in December 1941.' },
    { id: 'karafuto', atoms: ['karafuto'], cat: 'colony', lvl: 1,
      en: 'Karafuto (southern Sakhalin)', ja: '樺太 (Karafuto)', orig: 'Южный Сахалин',
      zh: '樺太（南薩哈林）', ko: '가라후토 (Karahuto)',
      when: 'Japanese 1905–1945',
      note: 'Coal, timber and fisheries, and the only land border Japan shared with the Soviet Union. Lost in August 1945.' },
    { id: 'kwantung', atoms: ['kwantung'], cat: 'colony', lvl: 2,
      en: 'Kwantung Leased Territory', ja: '関東州 (Kantōshū)', orig: '關東州 (Guāndōngzhōu)',
      zh: '關東州', ko: '관동주 (Kwandongju)',
      when: 'Leased 1905–1945',
      note: 'Still a separate Japanese leasehold, not part of Manchukuo: the lease was simply re-granted by the new state in 1932 and the territory kept its own administration to the end. Port Arthur and Dairen are inside it.' },
    { id: 'nanyo', atoms: ['nanyo'], cat: 'colony', lvl: 2,
      en: 'South Seas Mandate (Micronesia)', ja: '南洋群島 (Nan’yō Guntō)', orig: 'Micronesia',
      zh: '南洋群島', ko: '남양군도 (Namyang Kundo)',
      when: 'Mandate from 1919',
      note: 'Fortified through the 1930s in defiance of the mandate’s terms, and the base of the Combined Fleet at Truk. The Americans would take it atoll by atoll in 1943–44.' },

    { id: 'manchukuo', atoms: ['manchuria', 'jehol'], cat: 'puppet', lvl: 1,
      en: 'Manchukuo (Manchuria)', ja: '満洲国 (Manshūkoku)', orig: '滿洲國 (Mǎnzhōuguó)',
      zh: '滿洲國', ko: '만주국 (Manjuguk)',
      when: 'Puppet state from March 1932',
      note: 'Invaded from September 1931 and proclaimed independent under the last Qing emperor P’u-i. Jehol was added in 1933; the eastern Inner Mongolian leagues had been part of the three provinces all along and became its Hinggan provinces. Real power lay with the Kwantung Army and Japanese vice-ministers.' },
    { id: 'mengjiang', atoms: ['chahar', 'suiyuan'], cat: 'puppet', lvl: 2,
      en: 'Mengchiang (Mengjiang)', ja: '蒙疆 (Mōkyō)', orig: '蒙疆聯合自治政府',
      zh: '蒙疆聯合自治政府', ko: '몽강 (Monggang)',
      when: 'Client regime from 1936–39',
      note: 'The Inner Mongolian autonomous government under Prince Demchugdongrub, with its capital at Kalgan. Built out of the Chinese provinces of Chahar and Suiyuan.' },
    { id: 'nanjinggov', atoms: ['occupiedchina'], cat: 'puppet', lvl: 1, hatch: true,
      en: 'Japanese-occupied China (approximate)', ja: '日本占領地区 (approximate)', orig: '日軍佔領區 (approximate)',
      zh: '日軍佔領區（大略）', ko: '일본 점령지 (대략)',
      when: 'Occupied from 1937; Nanking government from March 1940',
      note: 'Governed on paper by Wang Ching-wei’s collaborationist government at Nanking. The boundary drawn here is deliberately coarse: Japanese control ran along the railway lines and around the cities, and Communist and Nationalist guerrillas held much of the countryside inside it.' },

    { id: 'indochina', atoms: ['indochina'], cat: 'occupied', lvl: 2,
      en: 'French Indochina', ja: '仏印 (Futsuin)', orig: 'Đông Dương thuộc Pháp',
      zh: '法屬印度支那', ko: '프랑스령 인도차이나 (P’ŭrangsŭryŏng Indoch’aina)',
      when: 'Occupied September 1940 – July 1941',
      note: 'Japanese troops entered the north in September 1940 and the south in July 1941 — the step that brought the American oil embargo. Vichy French officials stayed in place until March 1945.' },
    { id: 'burma', atoms: ['burma'], cat: 'occupied', lvl: 2,
      en: 'Burma', ja: '緬甸 (Biruma)', orig: 'မြန်မာ (Myanma)',
      zh: '緬甸', ko: '버마 (Pŏma)',
      when: 'Taken 1942; nominal independence August 1943',
      note: 'Separated from British India in 1937 and overrun in the first half of 1942, closing the Burma Road to Chungking. Ba Maw headed the nominally independent state declared in 1943.' },
    { id: 'malaya', atoms: ['malaya'], cat: 'occupied', lvl: 1,
      en: 'Malaya & Syonan-to (Singapore)', ja: '馬来 (Marai)・昭南島 (Shōnantō)', orig: 'Tanah Melayu / Syonan',
      zh: '馬來亞・新加坡', ko: '말라야·싱가포르 (Mallaya / Singgap’orŭ)',
      when: 'Invaded 8 December 1941; Singapore fell 15 February 1942',
      note: 'The seventy-day campaign down the peninsula ended in the largest capitulation in British military history. Singapore was renamed Syonan-to, "Light of the South"; the Sook Ching massacres of Chinese residents followed within weeks.' },
    { id: 'borneo_br', atoms: ['borneo_br'], cat: 'occupied', lvl: 3,
      en: 'British Borneo', ja: '北ボルネオ (Kita Boruneo)', orig: 'Borneo',
      zh: '英屬婆羅洲', ko: '영국령 보르네오 (Yŏnggungnyŏng Borŭneo)',
      when: 'Occupied December 1941 – January 1942',
      note: 'Taken first, and quickly, for the oilfields at Miri and Seria.' },
    { id: 'dei', atoms: ['dei'], cat: 'occupied', lvl: 1,
      en: 'Netherlands East Indies', ja: '蘭印 (Ran’in)', orig: 'Nederlandsch-Indië',
      zh: '荷屬東印度', ko: '네덜란드령 동인도 (Nedŏllandŭryŏng Tongindo)',
      when: 'Conquered January – March 1942',
      note: 'The object of the whole southern advance. The Dutch surrendered on 8 March 1942; Sukarno and other nationalists chose to work with the occupation.' },
    { id: 'philippines', atoms: ['philippines'], cat: 'occupied', lvl: 1,
      en: 'Philippine Islands', ja: '比島 (Hitō)', orig: 'Pilipinas',
      zh: '菲律賓', ko: '필리핀 (P’illip’in)',
      when: 'Invaded December 1941; Corregidor fell 6 May 1942',
      note: 'A US commonwealth. MacArthur withdrew to Australia in March 1942; a nominally independent republic under José Laurel followed in 1943.' },
    { id: 'hongkong', atoms: ['hongkong'], cat: 'occupied', lvl: 2,
      en: 'Hong Kong', ja: '香港 (Honkon)', orig: '香港 (Hēunggóng)',
      zh: '香港', ko: '홍콩 (Hongk’ong)',
      when: 'Attacked 8 December 1941, surrendered 25 December',
      note: 'Held for seventeen days and then occupied until 1945, its population halved by deportation and hunger.' },
    { id: 'timor_pt', atoms: ['timor_pt'], cat: 'occupied', lvl: 3,
      en: 'Portuguese Timor', ja: 'ポルトガル領チモール', orig: 'Timor Português',
      zh: '葡屬帝汶', ko: '포르투갈령 티모르 (P’orŭt’ugallyŏng T’imorŭ)',
      when: 'Occupied February 1942',
      note: 'Neutral Portuguese territory, invaded anyway after an Allied force landed there first. Tens of thousands of Timorese died in the campaign and the occupation.' },
    { id: 'guam', atoms: ['guam'], cat: 'occupied', lvl: 3,
      en: 'Guam (Omiya-jima)', ja: '大宮島 (Ōmiyajima)', orig: 'Guåhan',
      zh: '關島', ko: '괌 (Kwam)',
      when: 'Taken 10 December 1941',
      note: 'The one American possession inside the Japanese-held Marianas, renamed Ōmiyajima and retaken in 1944.' },
    { id: 'gilberts', atoms: ['gilberts'], cat: 'occupied', lvl: 3,
      en: 'Gilbert Islands', ja: 'ギルバート諸島', orig: 'Tungaru',
      zh: '吉爾伯特群島', ko: '길버트 제도 (Kilbŏt’ŭ Chedo)',
      when: 'Occupied December 1941',
      note: 'The outermost ring of the perimeter. The assault on Tarawa in November 1943 opened the American drive across the central Pacific.' },
    { id: 'nauru_au', atoms: ['nauru_au'], cat: 'occupied', lvl: 3,
      en: 'Nauru', ja: 'ナウル', orig: 'Naoero',
      zh: '諾魯', ko: '나우루 (Nauru)',
      when: 'Occupied August 1942',
      note: 'Held for its phosphate and then bypassed and starved; most of the population was deported to Truk.' },
    { id: 'andaman', atoms: ['andaman'], cat: 'occupied', lvl: 2,
      en: 'Andaman & Nicobar Islands', ja: '安達曼・ニコバル諸島', orig: 'Andaman & Nicobar',
      zh: '安達曼・尼科巴群島', ko: '안다만·니코바르 제도 (Andaman / Nik’obarŭ Chedo)',
      when: 'Occupied March 1942; ceded to Azad Hind December 1943',
      note: 'The only Indian territory Japan held. In December 1943 they were handed nominally to Subhas Chandra Bose’s Provisional Government of Free India and renamed Shaheed and Swaraj — "Martyr" and "Self-rule". The transfer was a gesture: the Japanese navy kept real control, and the occupation was harsh.' },

    { id: 'newguinea_au', atoms: ['newguinea_au'], cat: 'contested', lvl: 2,
      en: 'New Guinea (Papua & the Mandated Territory)', ja: 'ニューギニア', orig: 'Niugini',
      zh: '新幾內亞', ko: '뉴기니 (Nyugini)',
      when: 'Front line through 1942–45',
      note: 'Japan held the north coast and the great base at Rabaul; Australian and American forces held Port Moresby. The overland push across the Kokoda Track was turned back in September 1942.' },
    { id: 'solomons_br', atoms: ['solomons_br'], cat: 'contested', lvl: 2,
      en: 'Solomon Islands', ja: 'ソロモン諸島', orig: 'Solomon Islands',
      zh: '所羅門群島', ko: '솔로몬 제도 (Sollomon Chedo)',
      when: 'Fought over from August 1942',
      note: 'The Guadalcanal campaign, from August 1942 to February 1943, was the first sustained Allied offensive and the point at which the initiative changed hands.' },
    { id: 'aleutians', atoms: ['aleutians'], cat: 'contested', lvl: 3,
      en: 'Aleutian Islands', ja: 'アリューシャン列島', orig: 'Unangam Tanangin',
      zh: '阿留申群島', ko: '알류샨 열도 (Allyusyan Yŏldo)',
      when: 'Attu and Kiska occupied June 1942',
      note: 'Only the two westernmost islands were held — the sole North American soil Japan occupied — and they were retaken in 1943. The rest of the chain stayed American throughout.' },

    { id: 'thailand', atoms: ['siam'], cat: 'cobelligerent', lvl: 2,
      en: 'Thailand', ja: '泰国 (Taikoku)', orig: 'ประเทศไทย (Prathet Thai)',
      zh: '泰國', ko: '태국 (T’aeguk)',
      when: 'Alliance signed 21 December 1941',
      note: 'Invaded on 8 December 1941, it capitulated in hours, granted passage to the invasion of Malaya and Burma, allied with Japan and declared war on Britain and the United States. It was rewarded with territory in Malaya, Burma and Cambodia.' },

    { id: 'freechina', atoms: ['china'], cat: 'allied', lvl: 1,
      en: 'Free China (Nationalist government)', ja: '重慶政権 (Jūkei seiken)', orig: '國民政府 (Guómín zhèngfǔ)',
      zh: '國民政府（重慶）', ko: '자유중국 (Chayu Chungguk)',
      when: 'Capital at Chungking from 1938',
      note: 'The unoccupied interior, governed by Chiang Kai-shek from Chungking and supplied over the Burma Road until 1942 and then by air over "the Hump". The Communist base area lay around Yenan.' },
    { id: 'britishindia', atoms: ['india'], cat: 'allied', lvl: 1,
      en: 'British India', ja: '英領インド (Eiryō Indo)', orig: 'भारत (Bhārat)',
      zh: '英屬印度', ko: '영국령 인도 (Yŏnggungnyŏng Indo)',
      when: 'The western limit of the advance',
      note: 'The front stopped at the Burmese border in 1942. The Quit India movement was suppressed that August, while the Indian National Army formed on the other side.' },
    { id: 'ceylon', atoms: ['ceylon'], cat: 'allied', lvl: 3,
      en: 'Ceylon', ja: 'セイロン (Seiron)', orig: 'ලංකාව (Lanka)',
      zh: '錫蘭', ko: '실론 (Sillon)',
      when: 'Raided April 1942',
      note: 'The Indian Ocean raid of April 1942 struck Colombo and Trincomalee and drove the Royal Navy west to East Africa.' },
    { id: 'australia', atoms: ['australia'], cat: 'allied', lvl: 2,
      en: 'Australia', ja: '豪州 (Gōshū)', orig: 'Australia',
      zh: '澳大利亞', ko: '오스트레일리아 (Osŭt’ŭreillia)',
      when: 'Bombed from February 1942',
      note: 'Never invaded, but Darwin was bombed from February 1942 and Australia became the base from which the counter-offensive in New Guinea was mounted.' },
    { id: 'hawaii', atoms: ['hawaii'], cat: 'allied', lvl: 1,
      en: 'Hawaii', ja: '布哇 (Hawai)', orig: 'Hawaiʻi',
      zh: '夏威夷', ko: '하와이 (Hawai)',
      when: 'Attacked 7 December 1941',
      note: 'The US Pacific Fleet base at Pearl Harbor. The attack missed the carriers and the fuel farm, and both would decide the war within a year.' },

    { id: 'ussr', atoms: ['ussr'], cat: 'neutral', lvl: 1,
      en: 'Soviet Union (USSR)', ja: 'ソビエト連邦 (Sobieto Renpō)', orig: 'СССР (SSSR)',
      zh: '蘇聯', ko: '소련 (Soryŏn)',
      when: 'Neutrality Pact, April 1941',
      note: 'At war with Germany but not with Japan: the Neutrality Pact of April 1941 held until the Soviet invasion of Manchuria in August 1945. Both sides kept large armies on the Manchurian border throughout.' },
    { id: 'mongolia', atoms: ['mongolia'], cat: 'neutral', lvl: 2,
      en: 'Mongolian People’s Republic', ja: '蒙古人民共和国', orig: 'Бүгд Найрамдах Монгол Ард Улс',
      zh: '蒙古人民共和國', ko: '몽골인민공화국 (Monggol Inmin Konghwaguk)',
      when: 'Soviet satellite',
      note: 'Its border with Manchukuo was the scene of the undeclared war at Nomonhan in 1939, whose outcome helped turn Japanese strategy south rather than north.' },
    { id: 'xinjiang', atoms: ['xinjiang'], cat: 'allied', lvl: 3,
      en: 'Sinkiang (Xinjiang)', ja: '新疆 (Shinkyō)', orig: 'شىنجاڭ (Shinjang)',
      zh: '新疆', ko: '신장 (Sinjang)',
      when: 'Returned to Nationalist control in 1942',
      note: 'Governed since 1933 by Sheng Shicai in close alliance with the Soviet Union, which stationed troops there. Sheng changed sides in 1942 and brought the province back under Chungking’s authority; the road from the USSR through Xinjiang had been a supply line to China early in the war.' },
    { id: 'tibet', atoms: ['tibet'], cat: 'neutral', lvl: 3,
      en: 'Tibet', ja: 'チベット (Chibetto)', orig: 'བོད་ (Bod)',
      zh: '西藏', ko: '티베트 (T’ibet’ŭ)',
      when: 'De facto independent',
      note: 'Self-governing in practice and neutral in the war, it refused passage to an Allied supply route to China.' },
    { id: 'macau', atoms: ['macau'], cat: 'neutral', lvl: 3,
      en: 'Macao', ja: 'マカオ (Makao)', orig: '澳門 (Ou-mun)',
      zh: '澳門', ko: '마카오 (Mak’ao)',
      when: 'Neutral throughout',
      note: 'Portuguese and formally neutral, and so a refuge and a smuggling route — though under heavy Japanese pressure after Hong Kong fell.' },
    { id: 'other', atoms: ['other'], cat: 'other', lvl: 3,
      en: 'Afghanistan, Nepal and Bhutan', ja: 'アフガニスタン・ネパール・ブータン', orig: 'Afghanistan, Nepal, Bhutan',
      zh: '阿富汗・尼泊爾・不丹', ko: '아프가니스탄·네팔·부탄',
      when: '', note: 'Outside the story of the Japanese Empire, drawn for context.' },
  ],
};

/* ------------------------------------------------------------------ */
/* Cities, ports, battles and incidents                                */
/* ------------------------------------------------------------------ */
/* `year` is the first year the place matters for this course; the 1930 map
 * shows only what had happened by then. `date` is what the card displays. */

JMAP.SITES = [
  /* --- Japan -------------------------------------------------------- */
  { id: 'tokyo', cat: 'city', lvl: 1, lat: 35.68, lon: 139.76, year: 1868,
    en: 'Tokyo', ja: '東京 (Tōkyō)', orig: '東京 (Tōkyō)',
    zh: '東京', ko: '도쿄 (Tok’yo)',
    date: 'Capital from 1868',
    note: 'Edo until the Restoration. The Great Kantō earthquake struck in 1923 and was followed by the massacre of Koreans; the firebombing of 9–10 March 1945 killed some 100,000 people in a night.' },
  { id: 'yokohama', cat: 'city', lvl: 2, lat: 35.44, lon: 139.64, year: 1859,
    en: 'Yokohama', ja: '横浜 (Yokohama)', orig: '横浜 (Yokohama)',
    zh: '橫濱', ko: '요코하마 (Yok’ohama)',
    date: 'Treaty port opened 1859',
    note: 'The foreign settlement nearest Edo, and the terminus of Japan’s first railway in 1872.' },
  { id: 'uraga', cat: 'battle', lvl: 3, lat: 35.25, lon: 139.72, year: 1853,
    en: 'Uraga', ja: '浦賀 (Uraga)', orig: '浦賀 (Uraga)',
    zh: '浦賀', ko: '우라가 (Uraga)',
    date: 'July 1853',
    note: 'Where Commodore Perry’s squadron anchored and demanded that Japan open. He returned in February 1854 with a larger fleet.' },
  { id: 'shimoda', cat: 'city', lvl: 3, lat: 34.67, lon: 138.95, year: 1854,
    en: 'Shimoda', ja: '下田 (Shimoda)', orig: '下田 (Shimoda)',
    zh: '下田', ko: '시모다 (Simoda)',
    date: 'Opened 1854',
    note: 'One of the two ports opened by the Treaty of Kanagawa; Townsend Harris was the first American consul here, and negotiated the 1858 commercial treaty.' },
  { id: 'kyoto', cat: 'city', lvl: 2, lat: 35.01, lon: 135.77, year: 1868,
    en: 'Kyoto', ja: '京都 (Kyōto)', orig: '京都 (Kyōto)',
    zh: '京都', ko: '교토 (Kyot’o)',
    date: 'Imperial seat until 1868',
    note: 'The emperor’s city for over a thousand years, until the court moved to Tokyo. The Takikawa Incident at its Imperial University in 1933 marked the closing of academic freedom.' },
  { id: 'osaka', cat: 'city', lvl: 2, lat: 34.69, lon: 135.50, year: 1868,
    en: 'Osaka', ja: '大阪 (Ōsaka)', orig: '大阪 (Ōsaka)',
    zh: '大阪', ko: '오사카 (Osak’a)',
    date: 'Opened 1868',
    note: 'The commercial capital of Tokugawa Japan and later a centre of heavy industry and of labour organising.' },
  { id: 'kobe', cat: 'city', lvl: 3, lat: 34.69, lon: 135.20, year: 1868,
    en: 'Kobe', ja: '神戸 (Kōbe)', orig: '神戸 (Kōbe)',
    zh: '神戶', ko: '고베 (Kobe)',
    date: 'Treaty port opened 1868',
    note: 'Shipbuilding and the main emigration port for Japanese leaving for Hawaii and the Americas.' },
  { id: 'nagoya', cat: 'city', lvl: 3, lat: 35.18, lon: 136.91, year: 1889,
    en: 'Nagoya', ja: '名古屋 (Nagoya)', orig: '名古屋 (Nagoya)',
    zh: '名古屋', ko: '나고야 (Nagoya)',
    date: 'Bombed 1944–45',
    note: 'The centre of the aircraft industry, and for that reason among the most heavily bombed cities of the war.' },
  { id: 'hiroshima', cat: 'city', lvl: 1, lat: 34.39, lon: 132.46, year: 1894,
    en: 'Hiroshima', ja: '広島 (Hiroshima)', orig: '広島 (Hiroshima)',
    zh: '廣島', ko: '히로시마 (Hirosima)',
    date: 'Atomic bomb, 6 August 1945',
    note: 'Army headquarters and the embarkation port for the continent since 1894. Destroyed by the first atomic bomb; around 140,000 were dead by the end of the year.' },
  { id: 'nagasaki', cat: 'city', lvl: 1, lat: 32.74, lon: 129.87, year: 1641,
    en: 'Nagasaki', ja: '長崎 (Nagasaki)', orig: '長崎 (Nagasaki)',
    zh: '長崎', ko: '나가사키 (Nagasak’i)',
    date: 'Atomic bomb, 9 August 1945',
    note: 'The Dutch post at Dejima made this Japan’s only window on Europe under the Tokugawa. Destroyed by the second atomic bomb.' },
  { id: 'shimonoseki', cat: 'city', lvl: 2, lat: 33.96, lon: 130.94, year: 1864,
    en: 'Shimonoseki', ja: '下関 (Shimonoseki)', orig: '下関 (Shimonoseki)',
    zh: '下關', ko: '시모노세키 (Simonosek’i)',
    date: 'Bombarded 1864; treaty signed April 1895',
    note: 'Chōshū’s straits, shelled by a four-power squadron in 1864. The Treaty of Shimonoseki ended the First Sino-Japanese War and handed Formosa to Japan.' },
  { id: 'kagoshima', cat: 'city', lvl: 2, lat: 31.60, lon: 130.56, year: 1863,
    en: 'Kagoshima', ja: '鹿児島 (Kagoshima)', orig: '鹿児島 (Kagoshima)',
    zh: '鹿兒島', ko: '가고시마 (Kagosima)',
    date: 'Bombarded 1863; rebellion 1877',
    note: 'Castle town of Satsuma, shelled by the Royal Navy in 1863 over the Richardson Affair, and the base of Saigō Takamori’s rebellion in 1877.' },
  { id: 'hakodate', cat: 'city', lvl: 3, lat: 41.77, lon: 140.73, year: 1854,
    en: 'Hakodate', ja: '函館 (Hakodate)', orig: '函館 (Hakodate)',
    zh: '函館', ko: '하코다테 (Hak’odat’e)',
    date: 'Opened 1854; Republic of Ezo 1869',
    note: 'One of the first two ports opened to the Americans, and the site of the last Tokugawa resistance in the Boshin War.' },
  { id: 'sapporo', cat: 'city', lvl: 3, lat: 43.06, lon: 141.35, year: 1869,
    en: 'Sapporo', ja: '札幌 (Sapporo)', orig: '札幌 (Sapporo)',
    zh: '札幌', ko: '삿포로 (Satp’oro)',
    date: 'Founded 1869',
    note: 'Laid out on a grid as the headquarters of the Hokkaidō Colonisation Commission, the agency that settled the island and dispossessed the Ainu.' },
  { id: 'tsushima', cat: 'battle', lvl: 3, lat: 34.40, lon: 129.33, year: 1905,
    en: 'Tsushima Strait', ja: '対馬海峡 (Tsushima Kaikyō)', orig: '대한해협 (Taehan Haehyŏp)',
    zh: '對馬海峽', ko: '대한해협 (Taehan Haehyŏp)',
    date: '27–28 May 1905',
    note: 'Tōgō destroyed the Russian Baltic Fleet here after its eighteen-thousand-mile voyage — the decisive battle of the Russo-Japanese War and the first modern defeat of a European power by an Asian one.' },
  { id: 'naha', cat: 'city', lvl: 1, lat: 26.21, lon: 127.68, year: 1879,
    en: 'Naha (Okinawa)', ja: '那覇 (Naha)', orig: '那覇 (Naafa)',
    zh: '那霸', ko: '나하 (Naha)',
    date: 'Battle of Okinawa, April–June 1945',
    note: 'Port of the Ryūkyū Kingdom, and the site of the only land battle fought on Japanese home soil, in which around a quarter of Okinawan civilians died.' },
  { id: 'iwojima', cat: 'battle', lvl: 2, lat: 24.78, lon: 141.32, year: 1945,
    en: 'Iwo Jima', ja: '硫黄島 (Iō-tō)', orig: '硫黄島 (Iō-tō)',
    zh: '硫磺島', ko: '이오지마 (Iojima)',
    date: '19 February – 26 March 1945',
    note: 'Taken at a cost of nearly 7,000 American and over 18,000 Japanese dead, to give fighter cover to the bombers over Japan.' },

  /* --- Korea --------------------------------------------------------- */
  { id: 'seoul', cat: 'city', lvl: 1, lat: 37.57, lon: 126.98, year: 1876,
    en: 'Keijo (Seoul)', ja: '京城 (Keijō)', orig: '서울 / 한성 (Sŏul / Hansŏng)',
    zh: '京城（漢城）', ko: '서울 / 한성 (Sŏul / Hansŏng)',
    date: 'Renamed Keijō in 1910',
    note: 'Capital of Chosŏn Korea as Hansŏng, and of the colony as Keijō. The Kapsin Coup of 1884 and the March First Movement of 1919 both began here; Queen Min was murdered in the palace in 1895.' },
  { id: 'pusan', cat: 'city', lvl: 2, lat: 35.18, lon: 129.08, year: 1876,
    en: 'Fusan (Pusan)', ja: '釜山 (Fusan)', orig: '부산 (Pusan)',
    zh: '釜山', ko: '부산 (Pusan)',
    date: 'Opened by treaty 1876',
    note: 'The port closest to Japan, long the site of a Japanese trading enclave, and the southern end of the ferry and rail link that tied Korea into the Japanese economy.' },
  { id: 'incheon', cat: 'city', lvl: 3, lat: 37.46, lon: 126.71, year: 1883,
    en: 'Jinsen (Chemulpo, Incheon)', ja: '仁川 (Jinsen)', orig: '인천 / 제물포 (Inch’ŏn / Chemulp’o)',
    zh: '仁川', ko: '인천 / 제물포 (Inch’ŏn / Chemulp’o)',
    date: 'Naval action 9 February 1904',
    note: 'Seoul’s port, known to foreigners as Chemulpo. The Japanese attack on Russian ships here opened the Russo-Japanese War.' },
  { id: 'kanghwa', cat: 'battle', lvl: 3, lat: 37.75, lon: 126.48, year: 1876,
    en: 'Kanghwa Island', ja: '江華島 (Kōkatō)', orig: '강화도 (Kanghwado)',
    zh: '江華島', ko: '강화도 (Kanghwado)',
    date: 'Treaty signed 27 February 1876',
    note: 'Japanese gunboat diplomacy — an engineered incident in 1875, then a fleet — produced the Kanghwa Treaty, Korea’s own unequal treaty, on the model of the ones imposed on Japan twenty years before.' },
  { id: 'pyongyang', cat: 'city', lvl: 3, lat: 39.02, lon: 125.75, year: 1894,
    en: 'Heijo (Pyongyang)', ja: '平壌 (Heijō)', orig: '평양 (P’yŏngyang)',
    zh: '平壤', ko: '평양 (P’yŏngyang)',
    date: 'Battle, 15 September 1894',
    note: 'Site of a decisive Japanese victory over Qing forces in the First Sino-Japanese War, and later a centre of colonial industry and of Korean Christianity.' },

  /* --- Manchuria ----------------------------------------------------- */
  { id: 'mukden', cat: 'city', lvl: 1, lat: 41.80, lon: 123.43, year: 1905,
    en: 'Mukden (Shenyang)', ja: '奉天 (Hōten)', orig: '瀋陽 (Shěnyáng)',
    zh: '瀋陽（奉天）', ko: '봉천 (Pongch’ŏn)',
    date: 'Battle 1905; Manchurian Incident 18 September 1931',
    note: 'The Manchu dynastic capital, and the prize of the largest land battle of the Russo-Japanese War. The explosion staged on the South Manchuria Railway just outside the city on 18 September 1931 was the pretext for the invasion of Manchuria.' },
  { id: 'changchun', cat: 'city', lvl: 2, lat: 43.88, lon: 125.32, year: 1907,
    en: 'Hsinking (Changchun)', ja: '新京 (Shinkyō)', orig: '長春 (Chángchūn)',
    zh: '長春（新京）', ko: '장춘 / 신경 (Changch’un / Sin’gyŏng)',
    date: 'Capital of Manchukuo from 1932',
    note: 'Renamed Hsinking, "new capital", and rebuilt on a planned grid with boulevards and ministries as the showpiece of the puppet state.' },
  { id: 'harbin', cat: 'city', lvl: 2, lat: 45.80, lon: 126.53, year: 1909,
    en: 'Harbin', ja: 'ハルビン (Harubin)', orig: '哈爾濱 (Hā’ěrbīn)',
    zh: '哈爾濱', ko: '하얼빈 (Ha’ŏlbin)',
    date: 'Itō assassinated 26 October 1909',
    note: 'A Russian-built railway city with a large émigré population. Itō Hirobumi was shot at its station by the Korean independence activist An Chunggŭn. Unit 731 ran biological warfare experiments at Pingfang on the outskirts from 1936.' },
  { id: 'portarthur', cat: 'city', lvl: 1, lat: 38.82, lon: 121.22, year: 1894,
    en: 'Port Arthur (Ryojun, Lüshun)', ja: '旅順 (Ryojun)', orig: '旅順 (Lǚshùn)',
    zh: '旅順', ko: '뤼순 (Ryosun)',
    date: 'Siege, August 1904 – January 1905',
    note: 'Taken from China in 1894, given up under the Triple Intervention of 1895, leased by Russia in 1898, and won back at enormous cost in the siege of 1904–05. The pivot of Japanese continental policy for fifty years.' },
  { id: 'dairen', cat: 'city', lvl: 2, lat: 38.91, lon: 121.61, year: 1905,
    en: 'Dairen (Dalny, Dalian)', ja: '大連 (Dairen)', orig: '大連 (Dàlián)',
    zh: '大連', ko: '대련 (Taeryŏn)',
    date: 'Japanese from 1905',
    note: 'The commercial capital of the Kwantung Leased Territory and headquarters of the South Manchuria Railway Company, the vehicle of Japanese economic power in the region.' },
  { id: 'chengde', cat: 'city', lvl: 3, lat: 40.98, lon: 117.94, year: 1933,
    en: 'Chengteh (Chengde)', ja: '承徳 (Shōtoku)', orig: '承德 (Chéngdé)',
    zh: '承德', ko: '승덕 (Sŭngdŏk)',
    date: 'Occupied February 1933',
    note: 'The Qing emperors’ summer capital, and capital of Jehol province — English sources often call the city itself Jehol. Taken in a ten-day campaign and attached to Manchukuo; the Tanggu Truce followed in May.' },
  { id: 'nomonhan', cat: 'battle', lvl: 3, lat: 47.73, lon: 118.55, year: 1939,
    en: 'Nomonhan (Khalkhin Gol)', ja: 'ノモンハン事件 (Nomonhan jiken)', orig: 'Халхын гол',
    zh: '諾門罕', ko: '노몬한 (Nomonhan)',
    date: 'May – September 1939',
    note: 'An undeclared war on the Manchukuo–Mongolian border. Zhukov’s encirclement destroyed a Japanese division and helped settle the strategic argument in favour of striking south rather than north.' },
  { id: 'wanpaoshan', cat: 'battle', lvl: 3, lat: 44.95, lon: 125.40, year: 1931,
    en: 'Wanpaoshan', ja: '万宝山事件 (Manpōzan jiken)', orig: '萬寶山 (Wànbǎoshān)',
    zh: '萬寶山', ko: '만보산 (Manbosan)',
    date: 'July 1931',
    note: 'A quarrel over an irrigation ditch between Korean and Chinese farmers, inflamed by Japanese press reports into anti-Chinese riots in Korea, two months before the invasion of Manchuria.' },

  /* --- China ---------------------------------------------------------- */
  { id: 'beijing', cat: 'city', lvl: 1, lat: 39.90, lon: 116.40, year: 1900,
    en: 'Peking / Peiping (Beijing)', ja: '北京 (Pekin)', orig: '北京 / 北平 (Běijīng / Běipíng)',
    zh: '北京（北平）', ko: '북경 / 북평 (Pukkyŏng / Pukp’yŏng)',
    date: 'Renamed Peiping 1928; occupied July 1937',
    note: 'The Qing capital, demoted to "Peiping" when the Nationalists moved the capital to Nanking in 1928. Japanese troops joined the eight-nation force that relieved the legations in 1900, and took the city outright in 1937.' },
  { id: 'marcopolo', cat: 'battle', lvl: 2, lat: 39.85, lon: 116.21, year: 1937,
    en: 'Marco Polo Bridge (Lukouchiao)', ja: '盧溝橋事件 (Rokōkyō jiken)', orig: '盧溝橋 (Lúgōuqiáo)',
    zh: '盧溝橋', ko: '노구교 (Nogugyo)',
    date: '7 July 1937',
    note: 'A night exercise, a missing soldier and an exchange of fire — the skirmish that opened eight years of full-scale war in China.' },
  { id: 'tianjin', cat: 'city', lvl: 2, lat: 39.13, lon: 117.20, year: 1885,
    en: 'Tientsin (Tianjin)', ja: '天津 (Tenshin)', orig: '天津 (Tiānjīn)',
    zh: '天津', ko: '천진 (Ch’ŏnjin)',
    date: 'Convention 1885; occupied 1937',
    note: 'The treaty port for Peking, carved into eight foreign concessions including a Japanese one. The Tientsin Convention of 1885 regulated Chinese and Japanese troops in Korea and set the terms that broke down in 1894.' },
  { id: 'kalgan', cat: 'city', lvl: 3, lat: 40.81, lon: 114.88, year: 1937,
    en: 'Kalgan (Changchiakou, Zhangjiakou)', ja: '張家口 (Chōkakō)', orig: '張家口 (Zhāngjiākǒu)',
    zh: '張家口', ko: '장가구 (Changgagu)',
    date: 'Capital of Mengchiang from 1937',
    note: 'The old caravan gate through the Great Wall to Mongolia, and the seat of the Japanese-sponsored Inner Mongolian regime.' },
  { id: 'jinan', cat: 'city', lvl: 3, lat: 36.67, lon: 116.99, year: 1928,
    en: 'Tsinan (Jinan)', ja: '済南事件 (Sainan jiken)', orig: '濟南 (Jǐnán)',
    zh: '濟南', ko: '제남 (Chenam)',
    date: 'May 1928',
    note: 'Japanese troops sent to "protect residents" clashed with the Nationalist Northern Expedition; thousands of Chinese were killed, and a Chinese diplomat mutilated and executed.' },
  { id: 'qingdao', cat: 'city', lvl: 2, lat: 36.07, lon: 120.38, year: 1914,
    en: 'Tsingtao (Qingdao)', ja: '青島 (Seitō)', orig: '青島 (Qīngdǎo)',
    zh: '青島', ko: '청도 (Ch’ŏngdo)',
    date: 'Seized from Germany, November 1914',
    note: 'The German leasehold in Shantung, taken by Japan in 1914. Keeping it was the first of the Twenty-One Demands and was confirmed at Versailles, which set off the May Fourth Movement. Returned in 1922.' },
  { id: 'weihai', cat: 'city', lvl: 3, lat: 37.51, lon: 122.12, year: 1895,
    en: 'Weihaiwei (Weihai)', ja: '威海衛 (Ikaiei)', orig: '威海衛 (Wēihǎiwèi)',
    zh: '威海衛', ko: '위해위 (Wihaewi)',
    date: 'Battle, January–February 1895',
    note: 'The Peiyang Fleet’s base, destroyed by Japan in the closing weeks of the First Sino-Japanese War; afterwards a British leased territory until 1930.' },
  { id: 'nanjing', cat: 'city', lvl: 1, lat: 32.06, lon: 118.80, year: 1927,
    en: 'Nanking (Nanjing)', ja: '南京 (Nankin)', orig: '南京 (Nánjīng)',
    zh: '南京', ko: '남경 (Namgyŏng)',
    date: 'Fell 13 December 1937',
    note: 'Nationalist capital from 1927. Its capture was followed by weeks of mass killing and rape — the Nanking Massacre — and from 1940 it housed Wang Ching-wei’s collaborationist government.' },
  { id: 'shanghai', cat: 'city', lvl: 1, lat: 31.23, lon: 121.47, year: 1863,
    en: 'Shanghai', ja: '上海 (Shanhai)', orig: '上海 (Shànghǎi)',
    zh: '上海', ko: '상해 (Sanghae)',
    date: 'Fighting 1932; battle August–November 1937',
    note: 'The largest treaty port in China, with an International Settlement and a French Concession. Fighting in January 1932 and again in 1937, when three months of street and river fighting cost both armies enormously and destroyed China’s best divisions.' },
  { id: 'wuhan', cat: 'city', lvl: 2, lat: 30.58, lon: 114.28, year: 1861,
    en: 'Hankow (Wuhan)', ja: '漢口 (Hankō)', orig: '武漢 / 漢口 (Wǔhàn / Hànkǒu)',
    zh: '武漢（漢口）', ko: '무한 / 한구 (Muhan / Han’gu)',
    date: 'Fell 25 October 1938',
    note: 'The Nationalist government’s refuge after Nanking. Its fall ended the first mobile phase of the war; from then on the fighting in China settled into stalemate.' },
  { id: 'chongqing', cat: 'city', lvl: 2, lat: 29.56, lon: 106.55, year: 1891,
    en: 'Chungking (Chongqing)', ja: '重慶 (Jūkei)', orig: '重慶 (Chóngqìng)',
    zh: '重慶', ko: '중경 (Chunggyŏng)',
    date: 'Wartime capital 1938–1945',
    note: 'Chosen for the gorges and the fog that shielded it. Bombed for five years in one of the first sustained campaigns against a civilian population.' },
  { id: 'yanan', cat: 'city', lvl: 3, lat: 36.60, lon: 109.49, year: 1936,
    en: 'Yenan (Yan’an)', ja: '延安 (En’an)', orig: '延安 (Yán’ān)',
    zh: '延安', ko: '연안 (Yŏnan)',
    date: 'Communist base 1936–1947',
    note: 'The end of the Long March and the centre of Communist resistance, where Mao consolidated his leadership and the party grew from tens of thousands to over a million.' },
  { id: 'xian', cat: 'city', lvl: 3, lat: 34.34, lon: 108.94, year: 1936,
    en: 'Sian (Xi’an)', ja: '西安事件 (Seian jiken)', orig: '西安 (Xī’ān)',
    zh: '西安', ko: '서안 (Sŏan)',
    date: 'December 1936',
    note: 'Chiang Kai-shek was kidnapped here by his own generals and released only after agreeing to a united front with the Communists against Japan.' },
  { id: 'guangzhou', cat: 'city', lvl: 2, lat: 23.13, lon: 113.26, year: 1842,
    en: 'Canton (Guangzhou)', ja: '広東 (Kanton)', orig: '廣州 (Guǎngzhōu)',
    zh: '廣州', ko: '광주 (Kwangju)',
    date: 'Fell 21 October 1938',
    note: 'The original treaty port and the cradle of the Nationalist revolution, taken in 1938 to cut the supply line from Hong Kong.' },
  { id: 'xiamen', cat: 'city', lvl: 3, lat: 24.48, lon: 118.09, year: 1842,
    en: 'Amoy (Xiamen)', ja: '厦門 (Amoi)', orig: '廈門 (Xiàmén)',
    zh: '廈門', ko: '하문 (Hamun)',
    date: 'Occupied May 1938',
    note: 'A treaty port opposite Formosa, and a main point of departure for Chinese emigration to Southeast Asia.' },
  { id: 'hainan', cat: 'battle', lvl: 3, lat: 19.55, lon: 109.60, year: 1939,
    en: 'Hainan Island', ja: '海南島 (Kainantō)', orig: '海南島 (Hǎinándǎo)',
    zh: '海南島', ko: '해남도 (Haenamdo)',
    date: 'Occupied February 1939',
    note: 'Seized to blockade south China and as a stepping stone towards Indochina; worked with forced labour for its iron ore.' },

  /* --- Formosa --------------------------------------------------------- */
  { id: 'taipei', cat: 'city', lvl: 2, lat: 25.03, lon: 121.57, year: 1895,
    en: 'Taihoku (Taipei)', ja: '臺北 (Taihoku)', orig: '臺北 (Tâi-pak)',
    zh: '臺北', ko: '대북 (Taebuk)',
    date: 'Colonial capital from 1895',
    note: 'Seat of the Governor-General of Taiwan, and the administrative model that later colonies were built on.' },
  { id: 'kaohsiung', cat: 'city', lvl: 3, lat: 22.63, lon: 120.30, year: 1908,
    en: 'Takao (Kaohsiung)', ja: '高雄 (Takao)', orig: '高雄 (Ko-hiông)',
    zh: '高雄', ko: '고웅 (Koung)',
    date: 'Developed from 1908',
    note: 'The southern port built up by the colonial government, and the springboard for the "southward advance" into Southeast Asia.' },

  /* --- Russia / USSR --------------------------------------------------- */
  { id: 'vladivostok', cat: 'city', lvl: 2, lat: 43.12, lon: 131.89, year: 1918,
    en: 'Vladivostok', ja: '浦潮 (Urajio)', orig: 'Владивосток',
    zh: '海參崴', ko: '블라디보스토크 (Pŭlladibost’ok’ŭ)',
    date: 'Japanese landing, August 1918',
    note: 'Russia’s Pacific naval base and the terminus of the Trans-Siberian. The Siberian Intervention put 70,000 Japanese troops ashore here, and they stayed until 1922 — long after the other Allies had gone.' },
  { id: 'nikolaevsk', cat: 'battle', lvl: 3, lat: 53.14, lon: 140.73, year: 1920,
    en: 'Nikolaevsk-on-Amur', ja: '尼港事件 (Nikō jiken)', orig: 'Николаевск-на-Амуре',
    zh: '廟街（尼港）', ko: '니콜라옙스크 (Nik’ollayepsŭk’ŭ)',
    date: 'March – May 1920',
    note: 'Partisans killed the Japanese garrison and much of the Japanese and Russian civilian population. Japan used the massacre to justify occupying northern Sakhalin until 1925.' },

  /* --- Southeast Asia --------------------------------------------------- */
  { id: 'hanoi', cat: 'city', lvl: 2, lat: 21.03, lon: 105.85, year: 1902,
    en: 'Hanoi', ja: 'ハノイ (Hanoi)', orig: 'Hà Nội',
    zh: '河內', ko: '하노이 (Hanoi)',
    date: 'Japanese troops enter September 1940',
    note: 'Capital of French Indochina. Japan occupied the north to cut the rail supply route to Chungking, while leaving the French administration nominally in charge.' },
  { id: 'saigon', cat: 'city', lvl: 2, lat: 10.82, lon: 106.63, year: 1859,
    en: 'Saigon', ja: 'サイゴン (Saigon)', orig: 'Sài Gòn',
    zh: '西貢', ko: '사이공 (Saigong)',
    date: 'Occupied July 1941',
    note: 'The move into southern Indochina put Japanese bombers within range of Malaya and the Indies, and brought the American oil embargo and asset freeze that made war all but certain.' },
  { id: 'bangkok', cat: 'city', lvl: 2, lat: 13.75, lon: 100.50, year: 1782,
    en: 'Bangkok', ja: 'バンコク (Bankoku)', orig: 'กรุงเทพฯ (Krung Thep)',
    zh: '曼谷', ko: '방콕 (Pangk’ok)',
    date: 'Alliance signed 21 December 1941',
    note: 'Capital of the one uncolonised state in the region. Phibun’s government granted passage within hours of the invasion and allied with Japan a fortnight later.' },
  { id: 'singapore', cat: 'city', lvl: 1, lat: 1.29, lon: 103.85, year: 1819,
    en: 'Singapore (Syonan-to)', ja: '昭南島 (Shōnantō)', orig: 'Singapura',
    zh: '新加坡（昭南島）', ko: '싱가포르 (Singgap’orŭ)',
    date: 'Surrendered 15 February 1942',
    note: 'Britain’s great naval base, whose guns are often wrongly said to have pointed only out to sea; the real failures were air cover and the loss of the Prince of Wales and Repulse. 80,000 troops went into captivity.' },
  { id: 'kotabharu', cat: 'battle', lvl: 3, lat: 6.13, lon: 102.24, year: 1941,
    en: 'Kota Bharu', ja: 'コタバル (Kotabaru)', orig: 'Kota Bharu',
    zh: '哥打峇魯', ko: '코타바루 (K’ot’abaru)',
    date: '8 December 1941',
    note: 'The landing in northern Malaya began roughly an hour before the first bombs fell on Pearl Harbor — on the other side of the date line, so the calendars disagree.' },
  { id: 'manila', cat: 'city', lvl: 2, lat: 14.60, lon: 120.98, year: 1898,
    en: 'Manila', ja: 'マニラ (Manira)', orig: 'Maynila',
    zh: '馬尼拉', ko: '마닐라 (Manilla)',
    date: 'Occupied 2 January 1942',
    note: 'Declared an open city and occupied without a fight; devastated three years later during its recapture, when perhaps 100,000 civilians died.' },
  { id: 'corregidor', cat: 'battle', lvl: 3, lat: 14.38, lon: 120.57, year: 1942,
    en: 'Bataan & Corregidor', ja: 'バターン・コレヒドール', orig: 'Bataan / Corregidor',
    zh: '巴丹・科雷希多', ko: '바탄·코레히도르 (Bat’an / K’orehidorŭ)',
    date: 'April – 6 May 1942',
    note: 'The last American and Filipino stand. The surrender was followed by the Bataan Death March, in which thousands died.' },
  { id: 'leyte', cat: 'battle', lvl: 2, lat: 10.80, lon: 125.40, year: 1944,
    en: 'Leyte Gulf', ja: 'レイテ沖海戦 (Reite-oki kaisen)', orig: 'Golpo ng Leyte',
    zh: '雷伊泰灣', ko: '레이테만 (Reit’eman)',
    date: '23–26 October 1944',
    note: 'The largest naval battle ever fought. It destroyed the Imperial Navy as a fighting force and saw the first organised kamikaze attacks.' },
  { id: 'rangoon', cat: 'city', lvl: 2, lat: 16.87, lon: 96.20, year: 1852,
    en: 'Rangoon (Yangon)', ja: 'ラングーン (Rangūn)', orig: 'ရန်ကုန် (Yangon)',
    zh: '仰光', ko: '랑군 (Ranggun)',
    date: 'Fell 8 March 1942',
    note: 'Capital of British Burma and the port at the head of the Burma Road; its loss cut China’s last land supply line.' },
  { id: 'imphal', cat: 'battle', lvl: 2, lat: 24.82, lon: 93.94, year: 1944,
    en: 'Imphal & Kohima', ja: 'インパール作戦 (Inpāru sakusen)', orig: 'Imphal / Kohima',
    zh: '英帕爾', ko: '임팔 (Imp’al)',
    date: 'March – July 1944',
    note: 'The attempt to invade India, fought alongside Bose’s Indian National Army and launched without adequate supply. Some 55,000 Japanese casualties, most from starvation and disease — the worst defeat in Japanese military history to that point.' },
  { id: 'batavia', cat: 'city', lvl: 2, lat: -6.21, lon: 106.85, year: 1619,
    en: 'Batavia (Jakarta)', ja: 'ジャカルタ (Jakaruta)', orig: 'Batavia / Jakarta',
    zh: '巴達維亞（雅加達）', ko: '바타비아 (Bat’abia)',
    date: 'Dutch surrender, 8 March 1942',
    note: 'Capital of the Netherlands East Indies for three centuries. Sukarno and Hatta chose to work with the occupation, and declared independence two days after the surrender in 1945.' },
  { id: 'surabaya', cat: 'city', lvl: 3, lat: -7.25, lon: 112.75, year: 1942,
    en: 'Surabaya', ja: 'スラバヤ (Surabaya)', orig: 'Surabaya',
    zh: '泗水', ko: '수라바야 (Surabaya)',
    date: 'Battle of the Java Sea, 27 February 1942',
    note: 'The main Dutch naval base. The Allied squadron that sailed from here was annihilated, opening Java to invasion.' },

  /* --- The Pacific ------------------------------------------------------ */
  { id: 'pearlharbor', cat: 'battle', lvl: 1, lat: 21.35, lon: -157.95, year: 1941,
    en: 'Pearl Harbor', ja: '真珠湾攻撃 (Shinjuwan kōgeki)', orig: 'Puʻuloa',
    zh: '珍珠港', ko: '진주만 (Chinjuman)',
    date: '7 December 1941 (8 December in Japan)',
    note: 'Six carriers, two waves, two hours. Eight battleships hit and over 2,400 killed — but the American carriers were at sea and the fuel tanks and dockyards were left intact.' },
  { id: 'midway', cat: 'battle', lvl: 1, lat: 28.21, lon: -177.37, year: 1942,
    en: 'Midway', ja: 'ミッドウェー海戦 (Middowē kaisen)', orig: 'Pihemanu',
    zh: '中途島', ko: '미드웨이 (Midŭwei)',
    date: '4–7 June 1942',
    note: 'Four Japanese fleet carriers sunk in a single day, against one American. The offensive initiative in the Pacific never came back.' },
  { id: 'saipan', cat: 'battle', lvl: 1, lat: 15.19, lon: 145.75, year: 1944,
    en: 'Saipan', ja: 'サイパン (Saipan)', orig: 'Saipan',
    zh: '塞班島', ko: '사이판 (Saip’an)',
    date: '15 June – 9 July 1944',
    note: 'Its loss put Japan within B-29 range and brought down the Tōjō cabinet. Hundreds of Japanese civilians killed themselves at Marpi Point rather than surrender.' },
  { id: 'tinian', cat: 'battle', lvl: 3, lat: 15.00, lon: 145.62, year: 1944,
    en: 'Tinian', ja: 'テニアン (Tenian)', orig: 'Tinian',
    zh: '天寧島', ko: '티니안 (T’inian)',
    date: 'Taken July–August 1944',
    note: 'Its airfields, the busiest in the world by 1945, launched the atomic bomb missions to Hiroshima and Nagasaki.' },
  { id: 'truk', cat: 'battle', lvl: 3, lat: 7.42, lon: 151.78, year: 1944,
    en: 'Truk (Chuuk)', ja: 'トラック島 (Torakku-tō)', orig: 'Chuuk',
    zh: '特魯克', ko: '트루크 (T’ŭruk’ŭ)',
    date: 'Operation Hailstone, 17–18 February 1944',
    note: 'The Combined Fleet’s central Pacific anchorage — "the Gibraltar of the Pacific" — wrecked by carrier raids and then bypassed and left to rot.' },
  { id: 'peleliu', cat: 'battle', lvl: 3, lat: 7.00, lon: 134.25, year: 1944,
    en: 'Peleliu (Palau)', ja: 'ペリリュー (Peririyū)', orig: 'Beliliou',
    zh: '貝里琉', ko: '펠렐리우 (P’ellelliu)',
    date: 'September – November 1944',
    note: 'Expected to take four days and took over two months. It introduced the deep cave defence that would be used again on Iwo Jima and Okinawa.' },
  { id: 'wake', cat: 'battle', lvl: 2, lat: 19.28, lon: 166.65, year: 1941,
    en: 'Wake Island', ja: '大鳥島 (Ōtorishima)', orig: 'Wake Island',
    zh: '威克島', ko: '웨이크섬 (Weik’ŭ-sŏm)',
    date: 'Fell 23 December 1941',
    note: 'A small Marine garrison beat off the first landing before being overwhelmed. Ninety-eight captured civilian workers were murdered there in 1943.' },
  { id: 'kwajalein', cat: 'battle', lvl: 3, lat: 9.19, lon: 167.47, year: 1944,
    en: 'Kwajalein', ja: 'クェゼリン (Kuezerin)', orig: 'Kuwajleen',
    zh: '瓜加林', ko: '콰절런 (K’wajŏllŏn)',
    date: 'January – February 1944',
    note: 'The first pre-war Japanese mandate territory to be taken, breaching the outer ring of the defensive perimeter.' },
  { id: 'tarawa', cat: 'battle', lvl: 3, lat: 1.33, lon: 172.98, year: 1943,
    en: 'Tarawa', ja: 'タラワ (Tarawa)', orig: 'Tarawa',
    zh: '塔拉瓦', ko: '타라와 (T’arawa)',
    date: '20–23 November 1943',
    note: 'Seventy-six hours, over a thousand American dead on a coral islet of two square kilometres, and almost the whole garrison killed. The cost changed how the rest of the island campaign was planned.' },
  { id: 'rabaul', cat: 'city', lvl: 2, lat: -4.20, lon: 152.16, year: 1942,
    en: 'Rabaul', ja: 'ラバウル (Rabauru)', orig: 'Rabaul',
    zh: '拉包爾', ko: '라바울 (Rabaul)',
    date: 'Captured January 1942',
    note: 'Built into the great forward base of the South Pacific, with five airfields and over 100,000 troops. Bypassed from 1944 and left isolated until the surrender.' },
  { id: 'guadalcanal', cat: 'battle', lvl: 2, lat: -9.58, lon: 160.15, year: 1942,
    en: 'Guadalcanal', ja: 'ガダルカナル (Gadarukanaru)', orig: 'Guadalcanal',
    zh: '瓜達爾卡納爾', ko: '과달카날 (Kwadalk’anal)',
    date: 'August 1942 – February 1943',
    note: 'A half-built airfield became the first sustained Allied offensive of the Pacific War. Six months of attrition on land, sea and air that Japan could not afford; the withdrawal marked the turn of the tide.' },
  { id: 'portmoresby', cat: 'battle', lvl: 3, lat: -9.44, lon: 147.18, year: 1942,
    en: 'Port Moresby', ja: 'ポートモレスビー', orig: 'Port Moresby',
    zh: '莫爾茲比港', ko: '포트모르즈비 (P’ot’ŭmorŭjŭbi)',
    date: 'Coral Sea May 1942; Kokoda July–November 1942',
    note: 'The objective Japan never reached. The seaborne attempt was turned back at the Coral Sea and the overland push failed on the Kokoda Track, within sight of its goal.' },
  { id: 'darwin', cat: 'battle', lvl: 3, lat: -12.46, lon: 130.84, year: 1942,
    en: 'Darwin', ja: 'ダーウィン (Dāwin)', orig: 'Darwin',
    zh: '達爾文', ko: '다윈 (Tawin)',
    date: '19 February 1942',
    note: 'More bombs fell on Darwin than on Pearl Harbor, delivered by many of the same aircrew. Raids on northern Australia continued into 1943.' },
  { id: 'attu', cat: 'battle', lvl: 3, lat: 52.88, lon: 173.18, year: 1942,
    en: 'Attu', ja: 'アッツ島 (Attsu-tō)', orig: 'Atan',
    zh: '阿圖島', ko: '애투섬 (Aet’u-sŏm)',
    date: 'Occupied June 1942, retaken May 1943',
    note: 'Of some 2,600 defenders, fewer than 30 were taken alive. Tokyo called the annihilation gyokusai — "shattering the jewel" — and made it a model.' },
  { id: 'kiska', cat: 'battle', lvl: 3, lat: 51.97, lon: 177.53, year: 1942,
    en: 'Kiska', ja: 'キスカ島 (Kisuka-tō)', orig: 'Qisxa',
    zh: '基斯卡島', ko: '키스카섬 (K’isŭk’a-sŏm)',
    date: 'Occupied June 1942, evacuated July 1943',
    note: 'The garrison was lifted off under cover of fog before the Allied landing, which went ashore against an empty island and still took casualties from friendly fire.' },
];

/* ------------------------------------------------------------------ */
/* Per-epoch overrides                                                 */
/* ------------------------------------------------------------------ */
/* A place on the 1930 map should not be described by something that had not
 * happened yet, and some of them were not even called the same thing. These
 * override the name, date and note for one epoch; anything not listed here is
 * the same on both maps. */

JMAP.EPOCH_OVERRIDES = {
  tokyo: { e1930: {
    date: 'Capital from 1868',
    note: 'Edo until the Restoration, and still being rebuilt: the Great Kantō earthquake of 1923 destroyed much of the city and was followed by the massacre of several thousand Koreans by vigilantes and police.' } },
  hiroshima: { e1930: {
    date: 'Army headquarters from 1894',
    note: 'Base of the Fifth Division and the embarkation port for the continent. Imperial General Headquarters moved here during the war with China in 1894–95, and the emperor with it.' } },
  nagasaki: { e1930: {
    date: 'Dutch trade from 1641; treaty port 1859',
    note: 'The Dutch post at Dejima made this Japan’s only window on Europe under the Tokugawa. After 1859 a treaty port, and by 1930 a shipbuilding city dominated by the Mitsubishi yard.' } },
  naha: { e1930: {
    date: 'Okinawa Prefecture from 1879',
    note: 'Port of the Ryūkyū Kingdom. Japan abolished the kingdom in 1879, deposed its king and pensioned him off in Tokyo, and turned the islands into a prefecture.' } },
  kyoto: { e1930: {
    date: 'Imperial seat until 1868',
    note: 'The emperor’s city for over a thousand years, until the court moved to Tokyo after the Restoration.' } },
  nagoya: { e1930: {
    date: 'Castle town and industrial city',
    note: 'A Tokugawa castle town that became a centre of the textile trade and, later, of the aircraft industry.' } },

  seoul: { e1930: {
    date: 'Renamed Keijō in 1910',
    note: 'Capital of Chosŏn Korea as Hansŏng, and of the colony as Keijō. The Kapsin Coup of 1884 and the March First Movement of 1919 both began here; Queen Min was murdered in the palace in 1895.' } },

  mukden: { e1930: {
    date: 'Battle of Mukden, February–March 1905',
    note: 'The Manchu dynastic capital, and the prize of the largest land battle of the Russo-Japanese War. In 1930 it is the seat of Chang Hsüeh-liang’s government, with the Japanese South Manchuria Railway running through it and the Kwantung Army guarding the line.' } },
  changchun: { e1930: {
    en: 'Changchun', ja: '長春 (Chōshun)', orig: '長春 (Chángchūn)',
    zh: '長春', ko: '장춘 (Changch’un)',
    date: 'Railway junction',
    note: 'Where the Russian Chinese Eastern Railway met the Japanese South Manchuria Railway — the seam between the two spheres in Manchuria. It would be rebuilt as Hsinking, capital of Manchukuo, after 1932.' } },
  harbin: { e1930: {
    date: 'Itō assassinated 26 October 1909',
    note: 'A Russian-built railway city with a large émigré population, the biggest in the Russian Far East. Itō Hirobumi was shot at its station by the Korean independence activist An Chunggŭn.' } },

  beijing: { e1930: {
    date: 'Renamed Peiping in 1928',
    note: 'The Qing capital until 1912 and the seat of the warlord governments after it; demoted to Peiping — "northern peace" — when the Nationalists moved the capital to Nanking in 1928. Japanese troops had joined the eight-nation force that relieved the legations here in 1900.' } },
  nanjing: { e1930: {
    date: 'Nationalist capital from 1927',
    note: 'Capital of the Republic after the Northern Expedition, and the seat of Chiang Kai-shek’s government — such as its writ ran.' } },
  shanghai: { e1930: {
    date: 'Treaty port from 1843',
    note: 'The largest treaty port in China: an International Settlement run by its foreign ratepayers, a French Concession beside it, and the Chinese city around them. Japan had the largest foreign community in the city.' } },
  tianjin: { e1930: {
    date: 'Convention of 1885',
    note: 'The treaty port for Peking, carved into eight foreign concessions including a Japanese one. The Tientsin Convention of 1885 regulated Chinese and Japanese troops in Korea, and broke down in 1894.' } },
  guangzhou: { e1930: {
    date: 'Treaty port from 1842',
    note: 'The original treaty port and the cradle of the Nationalist revolution; the Northern Expedition set out from here in 1926.' } },
  wuhan: { e1930: {
    date: 'Treaty port from 1861',
    note: 'The tri-city on the middle Yangtze where the 1911 revolution began, and briefly the seat of the left Nationalist government in 1927.' } },
  chongqing: { e1930: {
    date: 'Treaty port from 1891',
    note: 'The head of steam navigation on the upper Yangtze, deep in the Sichuan interior and a fortnight from the coast.' } },
  xiamen: { e1930: {
    date: 'Treaty port from 1842',
    note: 'One of the first five treaty ports, and a main point of departure for Chinese emigration to Southeast Asia.' } },

  bangkok: { e1930: {
    date: 'Capital of Siam',
    note: 'Capital of the one state in the region never colonised; the Chakri kings had kept their independence by ceding territory to Britain and France in turn.' } },
  singapore: { e1930: {
    en: 'Singapore', ja: 'シンガポール (Shingapōru)', orig: 'Singapura',
    zh: '新加坡', ko: '싱가포르 (Singgap’orŭ)',
    date: 'Naval base begun 1923',
    note: 'Capital of the Straits Settlements and the site of the great naval base begun in 1923, on which the whole of British strategy east of Suez depended.' } },
  hanoi: { e1930: {
    date: 'Capital of French Indochina from 1902',
    note: 'Seat of the Governor-General of Indochina, and of the colonial administration that ran Tonkin, Annam, Cochinchina, Cambodia and Laos together.' } },
  saigon: { e1930: {
    date: 'French from 1859',
    note: 'Capital of Cochinchina, the oldest French possession in Indochina, and the rice-exporting port of the Mekong delta.' } },
  rangoon: { e1930: {
    en: 'Rangoon', ja: 'ラングーン (Rangūn)', orig: 'ရန်ကုန် (Yangon)',
    zh: '仰光', ko: '랑군 (Ranggun)',
    date: 'British from 1852',
    note: 'Capital of British Burma — still a province of British India in 1930 — and a great rice port with an Indian majority in its population.' } },
  manila: { e1930: {
    date: 'American from 1898',
    note: 'Capital of the American-ruled Philippines, taken from Spain in 1898 and promised eventual independence.' } },
  batavia: { e1930: {
    en: 'Batavia', ja: 'バタビア (Batabia)', orig: 'Batavia',
    zh: '巴達維亞', ko: '바타비아 (Bat’abia)',
    date: 'Dutch from 1619',
    note: 'Capital of the Netherlands East Indies and seat of the Governor-General, built by the Dutch East India Company on the ruins of Jayakarta.' } },
};

/* ------------------------------------------------------------------ */
/* Greatest extent of Japanese control, late 1942                      */
/* ------------------------------------------------------------------ */
/* Traced from the "War in the Pacific" map in Andrew Gordon, *A Modern History
 * of Japan: From Tokugawa Times to the Present* (Oxford University Press),
 * whose legend reads "Greatest extent of Japanese control, late 1942". Drawn
 * as a dashed line rather than a filled area because that is what it is: a
 * perimeter, generalised in Gordon and generalised again here. It runs out to
 * sea wherever the limit was naval rather than territorial, and across China it
 * follows a front that in reality was a broad, shifting and porous zone. */

JMAP.EXTENT_1942 = {
  en: 'Greatest extent of Japanese control, late 1942',
  ja: '日本の支配の最大範囲（1942年後期）',
  zh: '日本控制的最大範圍（1942年後期）',
  ko: '일본 지배의 최대 범위 (1942년 후반)',
  source: 'after Andrew Gordon, A Modern History of Japan',
  ring: [
    /* the front in China, from the Mongolian border southward */
    [106.6, 41.8], [106.9, 40.2], [108.4, 39.0], [110.2, 38.0], [110.6, 36.4],
    [110.8, 34.8], [111.6, 33.6], [112.4, 32.4], [111.6, 31.2], [110.6, 30.4],
    [111.8, 29.4], [113.2, 28.6], [114.6, 28.0], [116.0, 27.4], [117.6, 26.6],
    /* down the south-east coast, then the Canton and Hainan lobe */
    [118.6, 25.6], [119.4, 24.6], [117.6, 23.6], [116.0, 23.2], [114.6, 23.4],
    [113.2, 23.6], [111.6, 22.6], [110.4, 21.6], [110.6, 20.4], [111.0, 18.8],
    [110.0, 17.8], [108.4, 18.2], [108.2, 19.6], [108.7, 21.4],
    /* west along the northern edge of Indochina and Burma */
    [106.6, 22.8], [104.4, 23.0], [102.4, 22.6], [100.4, 22.2],
    [98.6, 24.0], [97.6, 25.8], [96.4, 27.2], [95.0, 26.4], [93.8, 24.6],
    [92.8, 22.4], [92.2, 20.0], [91.6, 17.0], [91.0, 13.0], [91.2, 9.0],
    /* out into the Indian Ocean, then south of Sumatra and Java */
    [92.6, 4.0], [94.4, 0.0], [97.0, -3.6], [100.6, -6.6], [105.0, -8.6],
    [110.0, -10.2], [115.0, -11.0], [120.0, -11.4], [125.0, -11.4],
    [130.0, -11.2], [135.0, -10.8], [140.0, -10.4],
    /* along the New Guinea and Solomons front */
    [144.0, -10.0], [147.4, -10.2], [151.0, -11.0], [155.0, -11.4],
    [159.0, -11.4], [163.0, -10.6], [167.0, -9.4], [171.0, -8.0],
    [175.0, -6.4], [179.0, -4.4], [180.6, -1.0],
    /* north along the dateline to the Aleutians */
    [181.0, 4.0], [181.2, 10.0], [181.4, 18.0], [181.4, 26.0], [181.2, 34.0],
    [180.8, 42.0], [180.2, 48.0], [178.6, 52.0], [174.0, 53.4], [170.0, 53.4],
    /* west along the Kurils to Kamchatka and down to Karafuto */
    [165.0, 52.6], [160.0, 52.0], [156.6, 50.8], [153.0, 48.0], [149.4, 45.8],
    [146.6, 44.4],
    /* across the Sea of Okhotsk to Karafuto, leaving the Soviet shore outside */
    [145.4, 47.0], [144.6, 50.2], [141.8, 50.2], [141.0, 49.2],
    /* down the Soviet Pacific coast to the Korean corner */
    [140.4, 48.6], [138.6, 47.0], [137.0, 45.6], [135.0, 44.3], [133.0, 43.0],
    [131.5, 42.7], [130.8, 42.4],
    /* back up the Ussuri and along the Amur: the Manchukuo frontier */
    [131.5, 44.2], [133.0, 45.3], [134.5, 47.5], [135.2, 48.4], [132.0, 48.5],
    [128.5, 49.8], [125.5, 53.0], [122.5, 53.5], [119.8, 52.6], [117.6, 49.6],
    /* and the Mongolian frontier of Manchukuo and Mengchiang */
    [115.6, 47.8], [117.4, 46.6], [118.8, 44.6], [117.0, 43.4],
    [115.0, 43.8], [113.0, 44.6], [110.6, 43.2], [108.4, 42.4],
  ],
};
