/* Generated by tools/build_relief.py. Do not edit.
   Shaded relief after Natural Earth, one warp per projection.
   x/y/w/h are the map units the image is drawn in. */
window.JMAP = window.JMAP || {};
JMAP.RELIEF = {
  "albers": {
    "h": 1680.75,
    "px": [
      4200,
      2313
    ],
    "src": "relief-albers.webp",
    "w": 3052.1,
    "x": 0.0,
    "y": 0.0
  },
  "laea": {
    "h": 1792.53,
    "px": [
      4200,
      2837
    ],
    "src": "relief-laea.webp",
    "w": 2653.47,
    "x": 0.0,
    "y": 0.0
  },
  "mercator": {
    "h": 1584.92,
    "px": [
      4200,
      2377
    ],
    "src": "relief-mercator.webp",
    "w": 2800.0,
    "x": 0.0,
    "y": 0.0
  }
};
