/* Generated by tools/build_relief.py. Do not edit.
   Shaded relief after Natural Earth.

   boxes:  where an image goes, in map units, per projection.
           A fact about the projection, not about the sheet,
           so all three levels share these.
   levels: coarsest first. `deg` is pixels per degree, which
           is what the browser sets the zoom fade from; `mb`
           is roughly what it costs to decode. */
window.JMAP = window.JMAP || {};
JMAP.RELIEF = {
  "boxes": {
    "albers": {
      "h": 1680.75,
      "w": 3052.1,
      "x": 0.0,
      "y": 0.0
    },
    "laea": {
      "h": 1792.53,
      "w": 2653.47,
      "x": 0.0,
      "y": 0.0
    },
    "mercator": {
      "h": 1584.92,
      "w": 2800.0,
      "x": 0.0,
      "y": 0.0
    }
  },
  "levels": [
    {
      "deg": 30.0,
      "kb": 641,
      "key": "coarse",
      "mb": 48,
      "note": "1:50m, 2 arc-minutes",
      "src": {
        "albers": "relief-coarse-albers.webp",
        "laea": "relief-coarse-laea.webp",
        "mercator": "relief-coarse-mercator.webp"
      }
    },
    {
      "deg": 45.0,
      "kb": 1607,
      "key": "fine",
      "mb": 107,
      "note": "1:10m, thinned to 4/5",
      "src": {
        "albers": "relief-fine-albers.webp",
        "laea": "relief-fine-laea.webp",
        "mercator": "relief-fine-mercator.webp"
      }
    },
    {
      "deg": 60.0,
      "kb": 2465,
      "key": "finest",
      "mb": 191,
      "note": "1:10m, 1 arc-minute",
      "src": {
        "albers": "relief-finest-albers.webp",
        "laea": "relief-finest-laea.webp",
        "mercator": "relief-finest-mercator.webp"
      }
    }
  ]
};
