"""The sugar company railways of Taiwan, 1929, as an SVG the map can graft.

    python3 tools/build_tw_sugar.py

The source is `tools/cache/1929_taiwan_sugar_rail_lines.geojson`, 534 lines in
EPSG:3826 — TWD97 / TM2 zone 121, which is metres and not degrees, so the first
thing done here is to put it back on the globe. TWD97 is within a metre of
WGS84 at this scale and no datum shift is applied.

These are not the government railway. They are the plantation lines: 762 mm
track laid by the sugar companies to bring cane to their mills, thousands of
kilometres of it across the western plain, some of it carrying passengers as a
sideline. They belong under the trunk line rather than beside it, and the map
draws them thinner and quieter for that reason.
"""
import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(HERE, "cache", "1929_taiwan_sugar_rail_lines.geojson")
OUT = os.path.join(ROOT, "japan-empire-map-tw-sugar.svg")

# --------------------------------------------------------------- EPSG:3826
A = 6378137.0                 # GRS80, which WGS84 shares to a tenth of a mm
F = 1 / 298.257222101
K0 = 0.9999
LON0 = math.radians(121.0)
FE, FN = 250000.0, 0.0


def inverse_tm(x, y):
    """TWD97 TM2 metres to degrees. The standard footpoint-latitude series."""
    e2 = F * (2 - F)
    ep2 = e2 / (1 - e2)
    e1 = (1 - math.sqrt(1 - e2)) / (1 + math.sqrt(1 - e2))
    m = (y - FN) / K0
    mu = m / (A * (1 - e2 / 4 - 3 * e2 ** 2 / 64 - 5 * e2 ** 3 / 256))
    phi1 = (mu
            + (3 * e1 / 2 - 27 * e1 ** 3 / 32) * math.sin(2 * mu)
            + (21 * e1 ** 2 / 16 - 55 * e1 ** 4 / 32) * math.sin(4 * mu)
            + (151 * e1 ** 3 / 96) * math.sin(6 * mu)
            + (1097 * e1 ** 4 / 512) * math.sin(8 * mu))
    c1 = ep2 * math.cos(phi1) ** 2
    t1 = math.tan(phi1) ** 2
    n1 = A / math.sqrt(1 - e2 * math.sin(phi1) ** 2)
    r1 = A * (1 - e2) / (1 - e2 * math.sin(phi1) ** 2) ** 1.5
    d = (x - FE) / (n1 * K0)
    lat = phi1 - (n1 * math.tan(phi1) / r1) * (
        d ** 2 / 2
        - (5 + 3 * t1 + 10 * c1 - 4 * c1 ** 2 - 9 * ep2) * d ** 4 / 24
        + (61 + 90 * t1 + 298 * c1 + 45 * t1 ** 2 - 252 * ep2 - 3 * c1 ** 2)
        * d ** 6 / 720)
    lon = LON0 + (d
                  - (1 + 2 * t1 + c1) * d ** 3 / 6
                  + (5 - 2 * c1 + 28 * t1 - 3 * c1 ** 2 + 8 * ep2 + 24 * t1 ** 2)
                  * d ** 5 / 120) / math.cos(phi1)
    return math.degrees(lon), math.degrees(lat)


# ------------------------------------------------------- the map's own frame
LON_MIN = 66.0
LAT_MAX = 55.0
PX_PER_DEG = 20.0
R = PX_PER_DEG * 180.0 / math.pi


def merc_y(lat):
    return R * math.log(math.tan(math.pi / 4 + math.radians(lat) / 2))


Y_TOP = merc_y(LAT_MAX)


def project(lon, lat):
    return ((lon - LON_MIN) * PX_PER_DEG, Y_TOP - merc_y(lat))


def main():
    if not os.path.exists(SRC):
        sys.stderr.write("build_tw_sugar: %s is missing\n" % SRC)
        return 1
    g = json.load(open(SRC, encoding="utf-8"))
    lines, points, kept = [], 0, 0
    box = [1e9, 1e9, -1e9, -1e9]
    for f in g["features"]:
        geom = f["geometry"] or {}
        parts = (geom.get("coordinates") or [])
        if geom.get("type") == "LineString":
            parts = [parts]
        name = (f.get("properties") or {}).get("NAME") or ""
        for part in parts:
            points += len(part)
            pts = []
            for x, y in part:
                lon, lat = inverse_tm(x, y)
                px, py = project(lon, lat)
                box[0] = min(box[0], lon); box[1] = min(box[1], lat)
                box[2] = max(box[2], lon); box[3] = max(box[3], lat)
                # two decimals is about a metre at the deepest zoom this map
                # allows, and is what every other path in the file carries
                p = (round(px, 2), round(py, 2))
                if not pts or p != pts[-1]:
                    pts.append(p)
            if len(pts) < 2:
                continue
            kept += len(pts)
            d = "M" + "L".join("%g %g" % p for p in pts)
            lines.append((name, d))

    body = "\n".join(
        '    <path%s d="%s"/>'
        % ((' data-name="%s"' % n.replace('"', "&quot;")) if n else "", d)
        for n, d in lines)
    svg = ('<svg xmlns="http://www.w3.org/2000/svg">\n'
           '  <!-- Generated by tools/build_tw_sugar.py. The sugar company\n'
           '       railways of Taiwan in 1929, in the map\'s own units. -->\n'
           '  <g id="tw-sugar">\n' + body + '\n  </g>\n</svg>\n')
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(svg)
    sys.stderr.write(
        "%d lines, %d of %d vertices kept (%.1f%%), %.0f KB\n"
        % (len(lines), kept, points, 100.0 * kept / max(1, points),
           os.path.getsize(OUT) / 1024.0))
    sys.stderr.write("extent %.3f–%.3f E, %.3f–%.3f N\n"
                     % (box[0], box[2], box[1], box[3]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
